### ISSUE TITLE
Stop viewer

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#114]
Currently it is possible to open the widget "stop viewer". However, the widget doesn't behave properly.

**Problem**
I was not able to select a stop. The widget always indicate "No stop selected". I tried multiple things to trigger the widget but it didn't work.

Also, when clicking a stop some information are display in a bubble. The Stop viewer widget needs to give different information to be useful or otherwise it is redundant. 

**Solution**
For now the access to the widget is going to be deleted. The user won't be able to open this widget on the production.

Illustration:
![image](https://cloud.githubusercontent.com/assets/1370401/10886032/366cfb28-814e-11e5-854a-601f7f17dfdd.png)

**Comment by jmfield2** [comment]
Is this when you click the 'stop viewer' link inside the marker popup (the link under 'alumni dr @ leroy in the screenshot), or when you click stop viewer from the gear/settings icon?

The former _should_ work, but I agree the latter does not.

**Comment by jailby** [comment]
Sorry, maybe I should mention in the issues I made that, for all, I access it via the gear button.

These issue are just here to keep a reminder that these widget won't be accessible but were there at some point (and thanks to  git can be fetch back).
