### ISSUE TITLE
Better visual of the menu

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#122]
The menu looks good but can be improved.

Between the buttons "Layers" and "Help" a separator would make it easier for the user to understand the two different category of action.

An icon for each menu button would be helpful. The same way that [this website is doing it](https://fossdroid.com/).

[Material Design Lite](http://www.getmdl.io/started/index.html) is providing a lot of [icons](http://google.github.io/web-starter-kit/latest/styleguide/icons/demo.html) that can be used for this purpose.

To insert the icons a tag need to be added. For example:
`<i class="material-icons">navigation</i>`

The following is a suggestion of icons that could be used to represent each action associated with a menu's button.

For "Trip planner":
![image](https://cloud.githubusercontent.com/assets/1370401/11038669/2769aeb2-86d2-11e5-940a-0de1be35aefa.png)
![image](https://cloud.githubusercontent.com/assets/1370401/11038700/4eb91ed0-86d2-11e5-9562-6d9cfc18618a.png)

For "Layers":
![image](https://cloud.githubusercontent.com/assets/1370401/11038715/63afc064-86d2-11e5-9489-940f054ea7cb.png)

For "Help":
![image](https://cloud.githubusercontent.com/assets/1370401/11038777/c3073ff6-86d2-11e5-8794-4f6c680531bc.png)

For "Send feedback":
![image](https://cloud.githubusercontent.com/assets/1370401/11038747/93a79ed6-86d2-11e5-842c-27a21cac439a.png)

If you have more suggestions concerning the icons you can post them as a reply to this post following the same format than used in here. (e.g.: For "nameOfButton": \n screenshot of icon)

**Comment by barbeau** [comment]
My personal preference is to have icons for the main "modes" of the application, and then a separator, and then the other categories (e.g., Settings, Help) without icons - see this screenshot of OneBusAway Android as a reference:

![image](https://cloud.githubusercontent.com/assets/928045/11039796/5d25b190-86d7-11e5-96a7-fc2e137b5139.png)

I prefer:

![image](https://cloud.githubusercontent.com/assets/1370401/11038700/4eb91ed0-86d2-11e5-9562-6d9cfc18618a.png)

...for trip planner.

**Comment by jailby** [comment]
How does this looks:
![image](https://cloud.githubusercontent.com/assets/1370401/11722424/a56026ee-9f36-11e5-9bba-366f1ae6e7c1.png)

It is not really pretty in term of code. I found a kind of hack by adding another li item with an hr tag in it. I can style the hr tag the way we want now. The thing that I don't find pretty about is the fact to have another item just for styling.
My first thoughs were to create two lists to separate them into categories but I haven't been able to make that solution work yet.

**Comment by barbeau** [comment]
For the separator, I'd prefer a lighter gray, like what's in the OneBusAway screenshot.

Also, we should take a look at changing the hamburger menu color from white to match the gold of the USF logo, or changing the USF logo to white.  I think the white hamburger with the gold logo looks a bit strange.

**Comment by barbeau** [comment]
Here are the colors used in the OneBusAway nav drawer, which I believe is consistent for standard Android design:

![image](https://cloud.githubusercontent.com/assets/928045/11039796/5d25b190-86d7-11e5-96a7-fc2e137b5139.png)

When an item with an icon is selected:
- Background color is set to `#11000000`
- Icon color is set to the theme color (for us, the USF green - `#006747`)
- Text color is set to the theme color (for us, the USF green - `#006747`)

When an item with an icon is NOT selected:
- Background color is set to white (`#ffffffff`)
- Icon color is set to `#888`
- Text color is set to black (`#ff000000`)

Separator is the color `#e5e5e5`.

Let's try these colors.
