### ISSUE TITLE
Better visibility of "switch fields" button

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#124]
From Renee Hunt at USF:

> The button to the right of the Start and End fields looks like a little phone rather than arrows.  Maybe take out the dark background behind the icon and make the arrows black on the gray button. 

I agree, it's currently hard to see.  I agree that making the arrow black on the gray button background is probably the best solution.

**Comment by jailby** [comment]
The switch button come from the following file(from official otp):
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/images/reverse.png

I was thinking about it and I see two option:

1) Modify the existing one
I personally don't like much the original but we could modify it to make it look better. Also making it bigger could help in term of visibility. 

2) Find a better one
I made only few search but I couldn't find one that I like yet.

**Comment by jailby** [comment]
I swapped the swap button from the upstream OTP one to the [material icon one](https://materialdesignicons.com/icon/swap-vertical).

I also made it bigger to increase its visibility (+4px for width and +6px for height). It is 30*30px atm, I tried other size and this one was the one that looked the best. It should look even better with more room to breath.
I'm currently working on adding a bit of space between the fields on the left and the button. So once that's done I will post another screenshot.

The following screenshot illustrate this swap:
![image](https://cloud.githubusercontent.com/assets/1370401/12852139/8590b68e-cbfb-11e5-9d9b-de14d03482c6.png)

**Comment by jailby** [comment]
So I added some breathing room and since I was there I added some space to fix #123.
There is more space above the start field, after the end field, and also between them.

Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/1370401/12855972/7cc5b850-cc10-11e5-8761-3f02fda256d7.png)

**Comment by jailby** [comment]
The following screenshot is the latest look of the switch button, and I think it looks good:
![image](https://cloud.githubusercontent.com/assets/1370401/12930678/b7056364-cf47-11e5-9d12-e79713cd7123.png)

I had some trouble getting the button to not be outside of the trip planner and therefore half hidden.

**Comment by jmfield2** [comment]
I think this is a big improvement actually - how did you fix it?

**Comment by jmfield2** [comment]
Actually the start arrow isn't aligned with the box (maybe it wasn't ever
lol) but otherwise looks pretty good

**Comment by jailby** [comment]
I had to play with the size of things a lot.

There is actually three object and that's why they were conflicting. There is a first div containing the button and then the image. I had to change the size margin and padding of these objects to get these result.

Also, the "drop down" button for the text field are of 1px I think. I need to look into it.

**Comment by barbeau** [comment]
Looking much better!

**Comment by jailby** [comment]
@barbeau what do you think of the problem that we are mentioning with @jmfield2 ?

I was looking into it but I haven't found how to fix it yet. The drop down button for the start field seem to be 2px down from where its suppose to be.

**Comment by barbeau** [comment]
@jailby I didn't even notice that, but you're right.  I'd try to tweak and make it align, but if it takes a long time to figure this out we can leave it for now.

**Comment by jailby** [comment]
So the dropdown button was a pixel lower and a pixel taller.

I fixed it and I will be pushing my change after this comment.

Here is a quick screenshot:

![image](https://cloud.githubusercontent.com/assets/1370401/12980160/3381ccea-d0a9-11e5-9fcc-0c8529454117.png)

**Comment by barbeau** [comment]
:+1:
