### ISSUE TITLE
Add "CUTR" as point-of-interest

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#127]
Right now "CUT" geocodes to the proper location, but the app doesn't recognize the more natural "CUTR".  I'll add this in a PR shortly.

**Comment by barbeau** [comment]
This is mainly an issue when the auto-complete doesn't trigger, and the lookup of locations happens when clicking on "Plan Your Trip".

**Comment by jmfield2** [comment]
Fixed by 6795dfdda320ac9513f16a8b396f0e84f7df1e33
