### ISSUE TITLE
Add credits to funding sources

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#129]
This one is definitely high priority - we need to acknowledge who funded the project.

We can include the following text somewhere:

> “We would like to acknowledge the support and funding assistance provided by the USF Student Green Energy Fund, Center for Urban Transportation Research, and Florida Department of Transportation.”

The question is where this goes.  I'd prefer to avoid adding more menu entries if possible.

@jailby @jmfield2 Any ideas?

**Comment by jailby** [comment]
I would see that in a category "about". However, if you don't want to add any other entry to the menu it could be fitted in the widget opened by "send feedback".

**Comment by jmfield2** [comment]
I would say either in send feedback or in the help widget since often about
information is found somewhere around help in other applications

There is also the welcome widget in case we want to more prominently show
this

**Comment by barbeau** [comment]
Yeah, let's try in the Help widget, and adding it to the Welcome widget also.

**Comment by jailby** [comment]
The credits have been added to the "help" widget and the following is a screenshot of the result:
![image](https://cloud.githubusercontent.com/assets/1370401/11749805/d13cd704-9ffd-11e5-9cdf-da6341cee20b.png)

**Comment by barbeau** [comment]
@jailby Thanks!  Could you add a reference to the commit with the addition here too?

**Comment by jailby** [comment]
f614f0b
