### ISSUE TITLE
Replace AT&T (?) favicon with a USF icon

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#130]
Strangely, for some reason the favicon for the app is now the AT&T logo??

![image](https://cloud.githubusercontent.com/assets/928045/11691599/bdcdbb4c-9e69-11e5-812b-d6b90e9a92f6.png)

This is high priority and should be a quick fix - this needs to change to a USF logo.

**Comment by barbeau** [comment]
We can use the same one that http://www.usf.edu/ is using:

![image](https://cloud.githubusercontent.com/assets/928045/11691651/f92278ae-9e69-11e5-94b4-a3cd5bf0024e.png)

**Comment by jailby** [comment]
For me it is the google logo:
![image](https://cloud.githubusercontent.com/assets/1370401/11697487/cfb99556-9e87-11e5-9a4d-9c59b6b5250c.png)

Can I inspect the element on usf.edu and take the logo or do we need to request it through UCM?
http://www.usf.edu/ucm/marketing/logos/other.aspx

**Comment by barbeau** [comment]
@jailby Yeah, go ahead and grab the logo directly from the site via insect element.

**Comment by jailby** [comment]
1982c04
