### ISSUE TITLE
"X" in Welcome window is invisible

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#145]
On maps.usf.edu, if you open the window in Incognito mode to imitate the first visit to the site, the "X" button to close the welcome window is invisible.  As a result, users can't close it and can't use the app.

We need to fix ASAP and roll out a new version to maps.usf.edu.

**Comment by barbeau** [comment]
@jmfield2 could you please help with this one to get a fix out quick?

**Comment by jmfield2** [comment]
Should be fixed by #146

**Comment by barbeau** [comment]
Thanks @jmfield2!!
