### ISSUE TITLE
Leaflet Locate Alert on Error

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#148]
The leaflet locate control currently still processes map geolocate hooks including errors (like when the user does not allow or denies the permission) and this causes an alert to popup (via alert();) which might be annoying/confusing for users.

I think a quick workaround/fix would be to replace the alert code with something less annoying like console.log - Do we want to do this, or keep the behavior as it is?

**Comment by jmfield2** [comment]
Another option is to change the error message to be more helpful.

I tested this behavior on an ios simulator (https://appetize.io/demo?device=iphone6plus&scale=50&orientation=portrait&osVersion=9.2) with safari and I was prompted for the location - 2-3 times.

I guess the GPS of the simulator has other issues but we should check that there isn't any other strangeness there.

**Comment by barbeau** [comment]
@jmfield2 What does console.log look like?

I think changing error message may be enough - something like "To see your real-time position on the map, please allow USF Maps to access your location".  Or something better than that :).
