### ISSUE TITLE
Enterprise Car Share Layer

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#159]
As an additional entry in the layers widget (for now), the following option should be added to toggle showing these two markers (in green):

Under "Other" heading (right, @barbeau ?)
"Enterprise Car Share"

(from https://www.enterprisecarshare.com/us/en/programs/university/usf.html)
![screenshot from 2016-02-05 01 44 29](https://cloud.githubusercontent.com/assets/3628509/12839725/301525f6-cbaa-11e5-994b-a271db73b79c.png)

**Comment by barbeau** [comment]
Yes, let's put this in a new category:
- Other
  - Enterprise CarShare

Others might have feedback after it goes live and we may need to change, but this is a good start.

**Comment by jmfield2** [comment]
The official map icons from that link seem to be:

https://www.enterprisecarshare.com/content/dam/ccw/icons/map-icons/map_active_pin.png

and

https://www.enterprisecarshare.com/content/dam/ccw/icons/map-icons/map_inactive.png

**Comment by jmfield2** [comment]
Lat,Lng positions also: 28.059951, -82.417575 and 28.064287, -82.412130

**Comment by jmfield2** [comment]
https://materialdesignicons.com/icon/car

**Comment by jailby** [comment]
Should this issue be closed?

**Comment by jmfield2** [comment]
Yes, I think this can be closed - IIRC the only thing left would be to add more dynamic functionality for locating cars via some API provided by Enterprise, but as of now we aren't aware of any.  If that changes, this can be reopened or split into another issue.
