### ISSUE TITLE
Parking Lots Layer & Points of Interest

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#160]
The various parking lots on campus should be added to layers corresponding to the permits that they allow.

S Non-Resident Student, R Resident Student, Y Park-n-Ride / Alumni, GZ - Gold Staff, E - Staff, 
D - Daily/Visitor
http://www.usf.edu/administrative-services/parking/documents/parkingmap.pdf

Also note, (related to #159) that other points are reflected such as the car share, hourly/metered parking, motorcycle, disabled, pay stations (although I think some (all?) now support parkmobile), electric charging stations, bike racks, bike repair stations, etc.

With that said, we need a way to add these into a data source somewhere that is easy/efficient to manage and integrate with the app.  The most likely place seems to be OSM itself (using amenity tags) and much of the data is already there.

From there, one possible option is to expand the internal OTP geocoder to query for these amenity tags when searching to recognize the POIs.  Note this is an open issue upstream and discussed somewhat in more detail @ https://github.com/opentripplanner/OpenTripPlanner/issues/2064

At least one benefit of this approach would be to also close #60 and migrate away from running the geocoder on a separate tomcat instance.

**Comment by jailby** [comment]
Charging phone stations. There is some in the MSC. These stations have multitple cables to plug phones.

**Comment by jailby** [comment]
This issue has been reported in a more global issue about the layers. #177 
Also, an issue about Parking has been created. #179

Therefore I am closing this issue.
