### ISSUE TITLE
Zoom Level and Layers UX Interaction

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#161]
I noticed that if for some reason you zoom to a level that the a given layer won't operate, there is no indication of this to the user when they attempt to toggle the layer on.

Some possible solutions to make this more friendly could be:
1) 'light' popup,
2) flash a message near the ribbon or at the top of the map,
3) indicate the layers items as unavailable/grayed

I believe in our discussion so far, #2 was the desired option and it also seems like it would be the least intrusive and easiest one to implement.

**Comment by barbeau** [comment]
I'm thinking something similar to this in shape and position, maybe with an alpha on the background:

![1454727841260-1858983489](https://cloud.githubusercontent.com/assets/928045/12870814/cb759146-cd23-11e5-9388-0db6880e19f8.jpg)
