### ISSUE TITLE
Add the hash #widget to the url

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#166]
When a user click on a specific widget from the menu, it's corresponding hash should be added at the end of the url.

Trip planner widget: http://maps.usf.edu/#trips
Layers widget: http://maps.usf.edu/#layers

Bonus when a user minimize a widget it would be even cooler if the hash was replaced by #map.
No widget shown: http://maps.usf.edu/#map

**Comment by barbeau** [comment]
+1 - main purpose of this is to enable users to easily copy/paste or
bookmark the individual widget views.
