### ISSUE TITLE
Add campus blue light phones as new layer

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#170]
Related to https://github.com/CUTR-at-USF/usf-mobullity/issues/160, but I'm splitting this out here due to priority.

Today USF requested that we add the blue light emergency phones as a new layer.  For now, let's call them "Blue Light emergency phones" under the "Other" category.

@jmfield2 Could you please prioritize this, and see if you can get it into production by the end of this week?

Hard-coding locations in config is ok if that's the fastest solution for now.  You can pull the data from OSM - the emergency phone locations for USF should be there with "amenity=emergency_phone" - also see [comment below](https://github.com/CUTR-at-USF/usf-mobullity/issues/170#issuecomment-181483046) for official map.

For this layer, we may actually want to manage the data separately from OSM, due to sensitivity of what might happen if someone moves the location in OSM and we unknowingly update maps.usf.edu with a bad location, and someone looks for the emergency phone in the wrong place.  Or, we could still use OSM, but add some type of point validation to notify  us if someone moves it in OSM, so we can confirm with USF Facilities or USFPD before updating maps.usf.edu.

**Comment by barbeau** [comment]
Let's use a blue marker for these with a white phone icon in the middle - normal material design phone icon should work:
https://materialdesignicons.com/icon/phone

If we want to get creative we could try including the alert icon in the marker as well (or just an exclamation point), but that's likely to get pretty crowded:
https://materialdesignicons.com/icon/alert

In the pop-up balloon, let's include the following text/link:

> **Use Blue Light Phones to contact Police**
> [More about campus safety](http://www.usf.edu/administrative-services/emergency-management/resources/campus-safety.aspx)

Also, I've asked for an official updated list of phone locations as lat/longs.  Here's a PDF of the official locations of USF blue light phones:
http://www.pplant.usf.edu/pdf/Emergency%20Blue%20Lights.pdf

We should cross-reference with this to make sure we're not missing any lights.

**Comment by jmfield2** [comment]
Here are some screenshots of two icon styles:

![screenshot from 2016-02-09 20 57 57](https://cloud.githubusercontent.com/assets/3628509/12937028/545df25a-cf72-11e5-8469-f42f0d312749.png)

![screenshot from 2016-02-09 20 40 08](https://cloud.githubusercontent.com/assets/3628509/12937029/5469bf68-cf72-11e5-85a1-74cbffd1296c.png)

I think I like the phone by itself..

Looks like it is almost ready to be merged w/ the static locations pulled from OSM

**Comment by barbeau** [comment]
Agreed, phone alone is better.  Looks good!

**Comment by barbeau** [comment]
@jmfield2 Here's the most recent blue light map:

[Blue Light Map-Tampa Campus.pdf](https://github.com/CUTR-at-USF/usf-mobullity/files/124893/Blue.Light.Map-Tampa.Campus.pdf)

Please be sure we're not missing any - also, please add any missing ones to OSM.  Thanks!

**Comment by jailby** [comment]
I believe that there is some of these blue light in parking garages but I don't see any in on the map.

E.g.: The parking garage by CUTR has emergency phones in the staircase by Alumni Dr. I'm not totally sure though. I don't see anything on the map about it.

**Comment by barbeau** [comment]
I'd stick to just the Blue Light phones (not all emergency phones) for this layer.  If we find a Blue Light phone that's not on the official USF map, we should probably clear it with USF first to make sure its not being removed or isn't fully functional.

**Comment by jmfield2** [comment]
PR is ready, I had to add 3 phones to OSM (https://www.openstreetmap.org/changeset/37168106) that were in the PDF ... I think the rest are there as far as I can tell.

The python code I used to quickly extract the latlngs from the OSM is:

```
from xml.etree.ElementTree import ElementTree

tree = ElementTree()
tree.parse("target/usf/map1.osm")

nodes = tree.findall("node")
phones = []
for n in nodes:
    p=n.findall(".//tag[@v='emergency_phone']")
    if p <> []: phones.append( "[%s,%s]" % (n.attrib['lat'], n.attrib['lon']) )

print ', '.join(phones)
```

**Comment by jailby** [comment]
I was talking about the following one:
![image](https://cloud.githubusercontent.com/assets/1370401/13008951/b1213b90-d167-11e5-8444-194e85f532b2.png)

This is in the parking garage by CUTR and its the staircase by Alumni Dr.

We can still merge #175 but at some point it would be good to update OSM and probably contact the persons in charge of this map because I don't think the map is accurate. I'm also surprised that there is no blue light around the engineering buildings.

**Comment by jmfield2** [comment]
:( ya I don't think these are listed anywhere on the PDF sean posted -- they probably should be, but I didn't do anything about that yet until we confirm that's what usf wants ...

I also noticed the big hole over ENG w/o any phones (at least on the map) ... maybe they are hiding, or it's by some strange design.

Also, when I uploaded my OSM changeset, jOSM complained about the tag (amenity=emergency_phone) being deprecated... I ignored it (since every other phone has the same tags), but it is perhaps something else to look into..

**Comment by barbeau** [comment]
Thanks @jailby for the picture!  I found a similar one in the northeast corner of parking garage by CUTR - the phone is in the stairwell, and the light is on the opposite side of the wall (outside the stairwell):

![image](https://cloud.githubusercontent.com/assets/928045/13016568/892977b2-d18d-11e5-90a3-ddbe45275645.png)

Let's stick with the official USF list for now, and merge it.  I'll follow up with USF to determine what to do with their other emergency phones, and about the gap in emergency.
