### ISSUE TITLE
Even margin above and under "Plan your trip" button

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#171]
task:
Even margin above and under "Plan your trip" button. 

I'm having a problem with it because the margin above appear because of the hr tag that creates the separator. The bottom margin of hr tags is .5em.
While the padding of the inner trip planner div tag is 5px.

I hesitated between changing the margin to 5px for hr tags and deleting this specific hr tag.
Changing the margin for all hr tags doesn't seem good to me because it could conflict with others hr tags.
Deleting this specific hr tag seemed the best option for me.

I delete the hr tag with the element inspector and it look good:
![image](https://cloud.githubusercontent.com/assets/1370401/12892379/c8ee5278-ce59-11e5-8fa8-32233aebe96e.png)

However, when I tried to actually delete this hr tag I also lost the button "Plan your trip". So I need to keep looking.

@barbeau are you in favor of deleting the hr tag? I would like to know before I keep trying to delete it.

**Comment by barbeau** [comment]
Removing hr tag is ok with me.  I think I like the look better with it (it separates action "Play trip" button from option controls), but without it is ok too.

**Comment by jailby** [comment]
So I tried to not removing the hr tag.

I was able to change the bottom border of the of the trip planner widget to `.5em`. My previous attempt where overshadow so that's why I couldn't do it.

Here is a screenshot of how the trip planner widget look like now:
![image](https://cloud.githubusercontent.com/assets/1370401/12921429/4d27a7f8-cf1b-11e5-8360-58de99d1ebc7.png)

**Comment by barbeau** [comment]
Looks good to me!
