### ISSUE TITLE
Light green within the layers widget

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#172]
Currently there is some light green inside of the layer widget:
![image](https://cloud.githubusercontent.com/assets/1370401/12931175/6043face-cf4a-11e5-8011-31956be761ab.png)

I changed it to black:
![image](https://cloud.githubusercontent.com/assets/1370401/12931213/8ecff0fa-cf4a-11e5-9e50-da89cf574ab3.png)

I also tried with the USF green but it so fine that we could only notice that it was "darkish".
Also, the first screenshot come from the production which doesn't have the border changed to gray yet.

The fix is coming soon.

**Comment by barbeau** [comment]
@jailby I'd prefer to have the inside lines that are currently light green be the same gray that's used for the exterior box border.  I think the black is too heavy - it shouldn't be the focus, just a light separator for the different types of information.

**Comment by jailby** [comment]
The following screenshot is with the gray instead of black (it still looks dark):

![image](https://cloud.githubusercontent.com/assets/1370401/12932755/600a7936-cf52-11e5-8869-be1c6b7548cc.png)

**Comment by jailby** [comment]
I feel like its hard to tell the difference because of the contrast with the white background.

**Comment by barbeau** [comment]
@jailby I agree - how about a lighter gray?

**Comment by barbeau** [comment]
Actually, are you sure that's gray?  Looks like black when I zoom in.

**Comment by jailby** [comment]
Sorry wrong screenshot:
![image](https://cloud.githubusercontent.com/assets/1370401/12933056/186bb6e2-cf54-11e5-8d3a-ca19491d4a63.png)

**Comment by barbeau** [comment]
I actually think that is reasonable. What do you think?

**Comment by jailby** [comment]
I tried with a ligther gray `#d3d3d3` and I can't decide which one is better:
![image](https://cloud.githubusercontent.com/assets/1370401/12933748/c7b2e960-cf57-11e5-96c4-3f33e44dad29.png)

For the sake of consistency I would choose the first gray but the light gray looks good too.

**Comment by barbeau** [comment]
I'd do the first gray - consistency is good, and I think the light gray is a little too light.  It doesn't provide as much visual separation at a glance.
