### ISSUE TITLE
Nominatim geocoder is broken

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#176]
From today, the secondary geocoding service (backed by Mapquest Nominatim) isn't working.  The reason is below:

_correction_ The 'true' in application-context.xml specifies to ONLY use the first result unless it is empty otherwise using all results in either case.

It looks like the API requires a key as of 9/15/15:

```
All Nominatim and Xapi requests require a key starting September 15, 2015. Please visit the MapQuest Developer Network to sign up for an AppKey if you do not have one.
```

http://open.mapquestapi.com/nominatim/

@barbeau should I sign up, or do you want to do this when you get a chance?  Also, how should this be stored? The URL is currently hard-coded into the geocoder repository and XML file ... probably not the best place for an API key - I'll try to think of a better place but let me know if you have any other ideas.

I haven't yet tested the system with a key, but I imagine this is the problem.

**Comment by barbeau** [comment]
I'm now remembering that we hit this same issue in OTP Android, and the lack of key was the problem.  I'll grab a key.  I'm fine with committing it to the repository - I'd there are issues we can change to something more secure later.

**Comment by barbeau** [comment]
Reopeining this - seems Nominatim geocoding is broken again on maps.usf.edu and mobullity.forest.usf.edu.  When typing in text that doesn't match USF buildings, "My Location" is the only option:
![image](https://cloud.githubusercontent.com/assets/928045/17971273/2ae5025c-6aa8-11e6-9906-5e392606ba9c.png)

I know the MapQuest OSM map tile API was deprecated - I'm assuming maybe the same happened for the Nominatim API?

**Comment by jmfield2** [comment]
Looks like it's the usage limit.

Going to the URL (http://open.mapquestapi.com/nominatim/v1/search?key=kOgk9LSvIeh3EbKOupBCxC5w4tB2JtF4) directly:

```
You have exceeded the number of monthly transactions included with your current plan. If you need additional transactions, please consider upgrading to a plan that offers additional transactions. If you would like to talk to an Account Manager about Enterprise Edition licensing options, please contact sales@mapquest.com.
```

**Comment by barbeau** [comment]
Bummer - thanks for tracking this down.  So I believe our other options for OSM-based geocoding are [Pelias](https://github.com/pelias/pelias) and Mapbox. 

I've been looking for an excuse to use Pelias in a project - we have a relationship with Mapzen and they've indicated a willingness to bump the usage limits for our projects, if we hit them, and there are some interesting research projects waiting to happen if we start using Pelias.  I just grabbed a key `search-zso6JBE` - could you give this a shot?

**Comment by barbeau** [comment]
BTW, looks like we saw a spike in usage on Aug 22, based on Google Analytics:

![image](https://cloud.githubusercontent.com/assets/928045/17972131/b96b9ae2-6aab-11e6-8226-802213baa4aa.png)

**Comment by jmfield2** [comment]
https://github.com/opendatalab-de/geojson-jackson

**Comment by barbeau** [comment]
@jmfield2 I've been working on a Java library for Pelias that will include all the response fields, and something we can use on Android too - I'll post here soon with the details.

**Comment by barbeau** [comment]
Alright, early version of Java library here:
https://github.com/CUTR-at-USF/pelias-client-library

I haven't had a chance to push the artifacts yet to the CUTR maven repo, so you won't be able to include the artifacts as shown in the README yet.  I'll try to do this tomorrow.

Please give it a try and let me know if it's missing any fields that we need.  There is currently a test `main` method in `PeliasRequest` that you can run to see example output.

**Comment by barbeau** [comment]
@jmfield2 I just pushed the `1.0.0-SNAPSHOT` artifacts for pelias-client-library to the CUTR mvn repo, so it should now be available to include in a project as shown in the README.

I think the main thing currently missing that you'll need in this project is the bounding box - it should be fairly simple to add.  I'll see if I can do this in the next day or so - if you want to tackle it just let me know via a comment.

**Comment by barbeau** [comment]
@jmfield2 FYI - I just saw that Mapzen has an explicit "autocomplete" API endpoint:
https://mapzen.com/documentation/search/autocomplete/

I'm asking what the difference between the two is, and I'll let you know when I hear.

Also, I'm refactoring the class names in the pelias-client-library to `SearchRequest` and `SearchResponse`, as these classes are currently for the Mapzen Search API.  This way we can support other API endpoints with a similar naming conventions.  So, if you update to the newest artifacts, you'll need to change the name accordingly.

**Comment by barbeau** [comment]
From https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/485#issuecomment-248416626:

> the two endpoints actually differ quite a bit in the query logic as well. With /autocomplete we assume that the user is not done typing the last token in the string and allow for more variation in the results. With /search we try to be more strict in our matches as we assume what the user sent across is complete and exactly what they intended (while accounting a bit for spelling errors).

We can use the `/search` endpoint for now, although it looks like we ideally want to be using `/autocomplete`.

**Comment by barbeau** [comment]
Just opened up https://github.com/CUTR-at-USF/pelias-client-library/issues/14 to add support for `/autocomplete` API in the pelias-client-library.
