### ISSUE TITLE
Add undocumented blue light emergency phone locations

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#184]
I asked USF Student Affairs about the blue lights we noticed in the Beard parking garage, and the absence of others in the engineering area, and they said:

> Plant thought there might have been changes, but did not have a more current map. I'd say add them for now. My office will work on tracking down a newer map or getting one made. 

So, let's add the ones we know about:
- https://github.com/CUTR-at-USF/usf-mobullity/issues/170#issuecomment-183348599
- https://github.com/CUTR-at-USF/usf-mobullity/issues/170#issuecomment-183443768

... and any others we come across.  We should add them to OSM as well as our hard-coded config here:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/widgets/tripoptions/LayersWidget.js#L170

@jailby Could you please work on this?

**Comment by jailby** [comment]
This has the highest priority? Behind the color changed we talked about?

I believe that parking garages have a blue light for each level of each of their stairwells. I'm not 100% sure but this is the case for the parking garage by cutr. Do you want me to go and physically check some parking garage? What about the Engineering area?
Or do you want me to just update the one by the parking garage and wait for USF Student Affairs to update the map?

**Comment by barbeau** [comment]
You can complete the current color task you are working on, and then do the
additional blue lights. Don't worry about tracking down additional blue
lights, just add the two that we know about.

**Comment by jailby** [comment]
I actually did the blue light first since its an OSM edit while for the rest I need to finish fixing the white space problem.
@jmfield2 you can pull data from OSM, update your branch, and PR.

**Comment by jmfield2** [comment]
:+1:  thanks!

Looks like you added 3, right? (two corners on north side and one on the south of the garage)

If so, ready to merge

**Comment by jailby** [comment]
Yes! I checked and for this garage there is one for each stairwell.
