### ISSUE TITLE
Leaflet Locate Control

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#195]
This issue deals with the behavior of the locate control button where you must toggle the behavior off/on, and where the default is on which also causes annoying map re-centering if the current location is off screen.

The behavior will change to as follows:
1) Automatic map panning to location is removed,
2) The only way to pan to your location is to click the locate control on the map - one time, and each time it is clicked subsequently,
3) The icon will change to a 'cross-hair' to more accurately reflect this new behavior: https://materialdesignicons.com/icon/crosshairs-gps

Location updates will still 'track' the user as it does now, with the exception of causing an automatic pan as described above.

**Comment by barbeau** [comment]
+1
