### ISSUE TITLE
Mobile UX 

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#200]
Some of the latest issues reported during the MyUSF app testing were related to UX/mobile responsiveness and the way the site currently doesn't resize/render in a standard way.  

Lacking 'pinch to zoom' because text was small being one of the issues

It turns out OTP maintains a separate front-end that might fix many of these issues - https://github.com/conveyal/otp.js

It uses the bootstrap JS/CSS library, and generally looks like this:

![screenshot from 2016-03-02 00 02 41](https://cloud.githubusercontent.com/assets/3628509/13518052/c498c266-e197-11e5-84ce-4b74f4b45f99.png)
![screenshot from 2016-03-02 00 02 44](https://cloud.githubusercontent.com/assets/3628509/13518053/c49a3092-e197-11e5-8282-0ce3fca8077d.png)
![screenshot from 2016-03-02 00 02 32](https://cloud.githubusercontent.com/assets/3628509/13518054/c49a14d6-e197-11e5-8ff3-bb2281246cdd.png)

**Comment by barbeau** [comment]
My understanding is that this site is an OTP client as well, although I don't believe I've looked at it on mobile:
http://www.carfreeatoz.com/planner

**Comment by jmfield2** [comment]
Note that according to the #308 google pagespeed rules, mobile ux is not a serious problem (98/100 score).

**Comment by barbeau** [comment]
Agreed, this is much better now then when you opened this issue - I'm closing.

**Comment by barbeau** [comment]
@jmfield2 Maybe I closed too soon, I thought this ticket was strictly about performance, but now I see we have notes on UI design as well - do you want to leave open?

**Comment by jmfield2** [comment]
We don't have to reopen - it was originally for usability and tracking the different approaches to the front-end design for mobile usability 

Since it is linked to the last suggestion, 295 I don't think we need to reopen
