### ISSUE TITLE
Can't pinch and zoom widget box contents

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#202]
From USF UCM:

> The inability to pinch and zoom the form for the trip planner could be an issue for vision-impaired users.

We should see if we can enable pinch to zoom on the trip planner, layers, and other widgets.

Assigning @jmfield2.

**Comment by jmfield2** [comment]
A small screenshot to show how this might work using hammerjs to catch pinch events ...  It still needs to be able to not overflow the window border (top, left) and not break the normal widget behaviors..

Also, the dropdown for e.g the trip start/end is not currently scaled as well.

![screenshot from 2016-03-11 09 07 16](https://cloud.githubusercontent.com/assets/3628509/13704305/2ae79b38-e769-11e5-90a6-88ae9d49529e.png)
