### ISSUE TITLE
"Plan trip" button style is different from other buttons

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#206]
From USF UCM:

> The “Plan your trip” button doesn’t match the look and feel of the other buttons.

We should make all the buttons have the same consistent style.  @jailby do you want to take this one?

**Comment by jailby** [comment]
Screenshot of the fix:
![image](https://cloud.githubusercontent.com/assets/1370401/13958889/30275c2e-f028-11e5-80e7-430e2da5dcb1.png)

The button "Plan Your Trip" has now the html/css default style instead of the javascript default style.

**Comment by barbeau** [comment]
Thanks @jailby!  Can you please add this screenshot to the PR as well?
