### ISSUE TITLE
Minimized widgets overlap content from other widgets

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#207]
For example, from UCM:

> If you use the drop down to select your location or destination, the Layers button at the bottom of the screen appears in front of the drop down list.

Here's what they are referring to:

![image](https://cloud.githubusercontent.com/assets/928045/13542541/6fbab44e-e231-11e5-91d2-50204b60ac44.png)

In today's meeting we agreed that we'd do a quick fix with z-order now, and later we'll review the behavior of the minimized widgets (possibly not showing the minimized window).

@jailby want to take this one?

**Comment by jailby** [comment]
Fixed.

Desktop:
![image](https://cloud.githubusercontent.com/assets/1370401/14020829/31b5a252-f1af-11e5-8c84-09581dac476a.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/14020847/4cbf5322-f1af-11e5-9ade-c7801ae87215.png)

**Comment by barbeau** [comment]
Cool!  Could you make the scroll bar visible on mobile?  And does it scroll on mobile?

**Comment by jailby** [comment]
Oh yeah sorry the scroll bar is off the screenshot. I'm gonna repost that soon.

**Comment by jailby** [comment]
I thought the scrollbar was on the right side but there is no scrollbar on mobile actually.

I didn't notice that.

But it's scrollling down fine.

**Comment by barbeau** [comment]
Ok - per our discussion I think we can still go with this solution.
