### ISSUE TITLE
"Bike safety" field always appears, even for non bike modes

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#211]
From USF UCM:

> “Drive only” still displays the drop down for “bicycle safety”.

![image](https://cloud.githubusercontent.com/assets/928045/13542768/28db2fac-e233-11e5-85e3-e1adabe66220.png)

We should do two things here:
1. Rename "Bike Safety" to "Prefer bike lanes", and change the selectable values to "Yes" or "No".  We really don't want to get into subjective things like "safety", so having a yes/no option for preferring bike lanes is a better presentation of this info.
2. Only show this drop down when a bike mode is selected in "Travel by:"

**Comment by jmfield2** [comment]
The PR makes the tripobjects dropdowns look like these screenshots.  Also note the PR comment that the bike lane control does not follow the same JS pattern, and should probably be changed at some point to do so.

![screenshot from 2016-03-18 08 05 31](https://cloud.githubusercontent.com/assets/3628509/13877796/75fd8dec-ece3-11e5-87b6-378161f1b11f.png)

![screenshot from 2016-03-18 08 05 26](https://cloud.githubusercontent.com/assets/3628509/13877799/7600b3f0-ece3-11e5-9f21-c8a92cd3c367.png)

![screenshot from 2016-03-18 08 05 20](https://cloud.githubusercontent.com/assets/3628509/13877798/76004960-ece3-11e5-9213-e6fd3109e675.png)

![screenshot from 2016-03-18 08 05 11](https://cloud.githubusercontent.com/assets/3628509/13877800/760102ec-ece3-11e5-8933-7b7c0f91fec2.png)

![screenshot from 2016-03-18 08 05 00](https://cloud.githubusercontent.com/assets/3628509/13877797/76004532-ece3-11e5-9c5c-2de898999ce3.png)

![screenshot from 2016-03-18 08 04 37](https://cloud.githubusercontent.com/assets/3628509/13877801/7602179a-ece3-11e5-9789-b919f518c58f.png)
