### ISSUE TITLE
Navigation between Trip Planner widget and Itinerary results aren't intuitive

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#212]
From USF UCM:

> The trip summary screen has no back or “edit trip” button. The minimize and close buttons are very close to each other with no ability to pinch and zoom.
> - _Realized later that closing the window is essentially the “Go back/edit”. This was unclear on first use. My expectation was that it would close the entire trip planner because the two windows are the same size/color._

The itinerary window on mobile can't be moved, and appears like this:

![image](https://cloud.githubusercontent.com/assets/928045/13542818/95b12898-e233-11e5-8c62-f747716ca741.png)

For a short-term fix, today we discussed changing the width of the Itineraries window so it wouldn't cover as much of the map, and staggering the placement a bit to show the Trip Planner widget behind it.  Perhaps something like this?

![image](https://cloud.githubusercontent.com/assets/928045/13542850/d5552620-e233-11e5-983a-4bd02586f151.png)

@jailby want to take a shot at this?

**Comment by jailby** [comment]
Done.

The itenerary returned widget appear significantly lower than trip widget to make the user realize that there is two widget and nothing from the information entered in the trip planner widget is lost.

Desktop:
![image](https://cloud.githubusercontent.com/assets/1370401/13708808/8ad400a8-e77e-11e5-858c-09fe93d3e2c5.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/13708793/8146efb4-e77e-11e5-9452-c48d088ffc3b.png)
