### ISSUE TITLE
Add USF permit types to geocoded Lot titles

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#213]
From USF UCM:

> Not identifying the different types of parking areas may cause confusion for anyone using this for driving and parking. Would recommend in the start/end, identifying what type of lot each is (i.e. Lot 2b (E)).

@jmfield2 I think you said you're working on this, related to #179?

**Comment by jmfield2** [comment]
fixed by https://github.com/CUTR-at-USF/usf-mobullity/commit/c2d2814dc1ed07ea2a878ff0e587cb08eb009435
