### ISSUE TITLE
Email isn't linked in "Send feedback" menu

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#214]
From USF UCM:

> The contact screen lists an email address, but tapping the email address does not open a new email, and there is no ability to copy the email address.

@jailby Want to take this?

**Comment by jailby** [comment]
I'm working on this issue and I encountered a "styling" problem.

I used:
`<a href="mailto:barbeau@cutr.usf.edu">Sean Barbeau</a>`

But this is coloring in blue because this is the common way to do so on website. However it does not look good on the USF green:
![image](https://cloud.githubusercontent.com/assets/1370401/13613228/3fca5e32-e539-11e5-8823-23e2b15297f5.png)

Should I change the text color to white? It might not be obvious to the user that the link is clickable.

Also I just put "Sean Barbeau" but I think it might be helpful for people to also be able to copy/paste into their mailling application your email. What do you think? If yes you need to cancel the ability to move the widget.

**Comment by barbeau** [comment]
I'd change the title to "Send feedback" (to match the menu), and I'd change the body to:

> We welcome questions and comments!  Send feedback to Sean Barbeau (barbeau@cutr.usf.edu).

All white, but bold the "Sean Barbeau (barbeau@cutr.usf.edu)".

I don't think copy/paste is needed, as long as clicking/tapping my name/email works.

**Comment by barbeau** [comment]
Actually, while you're here, let's add a small bit about the open-source project:

> We welcome questions and comments! Send feedback to Sean Barbeau (barbeau@cutr.usf.edu).
> 
> Like hacking things?  This project is open-source - see how you can help at [usf-mobullity on Github](https://github.com/CUTR-at-USF/usf-mobullity).

**Comment by jailby** [comment]
I'm having a problem with this. Under chrome the link only open a new window.
From my understanding of the problem my email service under chrome is not setup properly.
I'm not totally sure how to solve this problem yet. I'm looking into it.

Also it is possible to populate some fields for the email like subject and body.
@barbeau Let me know if you want a specific subject (e.g.:"[mobulity] feedback").

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1370401/13639349/595145aa-e5de-11e5-9a06-288e1a7afb5f.png)

**Comment by jailby** [comment]
I use mainly gmail so I have the problem describe [here](https://developers.google.com/web/updates/2012/02/Getting-Gmail-to-handle-all-mailto-links-with-registerProtocolHandler?hl=en). They give a solution but for the user to fix the problem.

I don't know if there is a lot of people in my case and/or if we need to do something about but I'm stil looking for a solution "server-side".

**Comment by barbeau** [comment]
@jailby Good idea - let's use "USF Maps feedback" as the subject line.

For body, can you pull attributes from the browser, like platform (Windows vs. Mac, etc, and version), whether it's mobile or not, if they are on cellular or WiFi or hard-wired, and the real-time location of the user?  Our app version, including OTP commit id?  And anything else that might be helpful for troubleshooting?  We shouldn't include MAC address or anything else that's privacy sensitive.

We can stick this at the bottom of the email, so the body looks like:

> ...empty space
> 
> ## The below information helps us troubleshoot problems.
> 
> Windows 7 Pro - Chrome v28.3238.34 ...

**Comment by barbeau** [comment]
@jailby Yes, not sure you can really do much about the desktop mailto issue.  Does it work on mobile?

**Comment by jailby** [comment]
Ok, I think that's a really good idea.

I'm gonna look into this. I will try to pull each of the following information:
- [x] browser
- [x] OS with version (thus mobile vs desktop)
- [ ] network (cellular, WiFi or wire)
- [ ] location of the user
- [ ] our app version (fetch the commit id)
- [ ] else?

**Comment by barbeau** [comment]
- [ ] Device type (e.g., Samsung Galaxy S5) too, if that's possible.  This is especially important on mobile.

**Comment by jailby** [comment]
Update: I was able to get the browser (with its version) and the the OS (with its version). The device type is apparently sometimes included in the browser version.
I'm having trouble to get the lat and long of the user and the app version. I'm still working on it.

The following are the screenshot of the mail application opened by the link for desktop and mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/13677013/4ef5f00a-e6b6-11e5-8221-772567d5144c.png)

![image](https://cloud.githubusercontent.com/assets/1370401/13677030/6374f378-e6b6-11e5-8d99-896585ac41d5.png)

The information are formated as follow:
Browser CodeName + Browser Version
The Browser Version contain a lot of information to describe precisely the version of the browser. OS and sometimes device.

I can format these information differently but if I have Browser Version + Platform it will be redundant. 

Also, the cursor position in the mail client will depend on the mail client only. Apparently, we do not have any control over it. 

I still need to look but it does not look promising for network type.
We could ask directly the user by having something like: 

> Please provide the following information:
> Network type (wifi, cellular, wired) :

**Comment by barbeau** [comment]
Don't worry about network type or location if those are problematic.

**Comment by jailby** [comment]
@barbeau so do you want me to ship it as it is now?

**Comment by barbeau** [comment]
Yes - let's format it as follows:

```
------
The below information helps us troubleshoot problems:
xxxxxxx
```
