### ISSUE TITLE
Widget z-ordering is wrong (layers, trip planner, help and contact)

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#216]
From USF UCM:

> Modal windows layer on top of each other (layers, trip planner, help and contact)

![image](https://cloud.githubusercontent.com/assets/928045/13543106/32a5a992-e236-11e5-82b9-3e161a60c69c.png)

"Help" and "Send Feedback" appear behind the "Trip Planner" and "Layers" widgets.  They should appear in front.

@jailby want to take this?

**Comment by jailby** [comment]
This issue should be closed since we changed the behavior of having only one widget at the time in #218 .
