### ISSUE TITLE
Unavailable tiles replaced by gray block

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#219]
Sometimes some tiles are unavailable. Thus, the server don't print the image corresponding to the tile and the area is gray.

The code block for the configuration of the tile can be found [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L50).

I looked into it and the unavailable tile come from subdomain.

Example:
![image](https://cloud.githubusercontent.com/assets/1370401/13574970/8034689a-e454-11e5-9b29-e5fb99a2af9c.png)

The error message received:
![image](https://cloud.githubusercontent.com/assets/1370401/13574997/99981dd6-e454-11e5-9b5a-1546bbb73a67.png)

**Comment by barbeau** [comment]
This could also potentially be fixed by switching tile providers, as mentioned in https://github.com/CUTR-at-USF/usf-mobullity/issues/203.

**Comment by jmfield2** [comment]
I think upstream leaflet issue

https://github.com/Leaflet/Leaflet/issues/3977

Might be related

**Comment by barbeau** [comment]
We can call this resolved for us, as we switched from MapQuest OSM to the MapBox tiles in https://github.com/CUTR-at-USF/usf-mobullity/pull/297, so we no longer have this problem.  I believe MapQuest also end-of-life'd this service we were pulling tiles from, so this issue may no longer be present in the MapQuest tile service that requires an API key.  If we ever switch back to MapQuest tiles and have this issue we can re-open.
