### ISSUE TITLE
Mobile responsiveness of client

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#22]
Investigate speed/lag issues of mobullity on mobile devices and determine if speedups can be made to i.e: the ajax calls currently in use and whether they really need to be updated upon refresh, or if the underlying tile layer itself is suspect.

**Comment by barbeau** [comment]
From earlier testing/discussion it seems like the bus stops layer is the main culprit here.  If you zoom out to the level at which the stops aren't displayed, then things are very responsive on mobile.  But, when zooming in, currently all Bull Runner stops and HART stops are visible (at least in the most recent version I've seen).  

It seems like the best first step to tackle this is to turn all stops off by default, and only show stops for the currently selected Bull Runner route(s).  And, have a separate check box to turn on HART bus stops.  For the majority of users I think this alone would be a significant improvement.

**Comment by barbeau** [comment]
I'm no longer having performance issues on the most recent Android phones I've been using (LG G3 and LG G4).  @jmfield2 and @jailby could you please try the site on your phones and see if you have any performance problems when displaying the various layers and trip plans?

I think turning off all the bus stops by default resulted in a huge performance bump.

**Comment by jailby** [comment]
I don't notice any major performance issue. 

I displayed multiple layers and plan multiple trips.

**Comment by jmfield2** [comment]
This issue seems to be fixed after the latest stop layer changes and other improvements.  

Still to do are broken out into other issues:
- #200 and #295 for mobile UX improvements via major frontend changes
- #308  Google Pagespeed improvements
