### ISSUE TITLE
Change to MapBox for Map Tile Provider

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#223]
Split out from #203 

This issue is to investigate switching from the current mapquest tiles to mapbox.  Screenshots in the other issue of progress so far.

**Comment by jailby** [comment]
I was able to use one their default map. Screenshot:

![image](https://cloud.githubusercontent.com/assets/1370401/14711534/a54f3288-07a7-11e6-84a6-e1f12e38ae8f.png)

I was also able to create a new style with the mapbox editor tool:
![image](https://cloud.githubusercontent.com/assets/1370401/14711584/d4aba94e-07a7-11e6-98b6-4726e450cbb0.png)

The editor tools seem really powerful. I played whit it and I will present it during our meeting.

So far I haven't been able to specify the tile style to be the one I created. I use the default styles given on mapbox website.

**Comment by barbeau** [comment]
Cool!  I think to see a custom style in the app it has to be created under the same account as the map API key.  So to test you can either switch to your own API key or I can create the same style under my account, if you share the map CSS.

As far as customization, for now I think the only thing we will want to change from the default is to add building names - I believe this is the only thing that the current tiles have that default MapBox tiles do not.

**Comment by jailby** [comment]
Yes in the designer tool, it is possible to get the map tiles url and the map API key. 

For the custom map that will go on production, I think that it should be a map from your account with your API key.

The designer tools has the possibility to share map. Someone can modify the style of the current production and then propose his/her new style. This could work in a similar way than Github (without the versions control).

**Comment by barbeau** [comment]
For quotas, here's a summary of what we get on MapQuest vs. MapQuest:
- **MapQuest** - Free plan - 15,000 transactions/month for free.  This includes both map tile requests and geocoding requests - we're currently using MapQuest for both.
- **Mapbox** - Standard plan (free for us via educational discount) - 100k map views or 75k mobile users / month, 5GB storage | 20 styles

So it seems switching to Mapbox would actually help us from a quota perspective as well.

**Comment by jailby** [comment]
Investigation done.

Issue to modify the tile provider at #266
