### ISSUE TITLE
Send Feedback and Help widget size on mobile

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#225]
I thought we talked about this problem but I didn't find an issue about it.

The **height** of the Send Feedback and Help widget on mobile are too big.

Screenshot of the prb:
![image](https://cloud.githubusercontent.com/assets/1370401/13709216/b3eed092-e780-11e5-9a80-5da02fcf462c.png)

Screenshot of the fix:
![image](https://cloud.githubusercontent.com/assets/1370401/13709206/aae1b366-e780-11e5-8fc0-f73e2ffbf2e0.png)

The PR is coming.

**Comment by barbeau** [comment]
+1
