### ISSUE TITLE
Times on "itenerary returned" widget are too small

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#239]
The times on "itenerary returned" widget are too small:
![image](https://cloud.githubusercontent.com/assets/1370401/14052782/1b9c9832-f2a3-11e5-9446-acdea11d7031.png)

**Comment by barbeau** [comment]
Here's the exact quote from UCM:

> The start and end time on trip summary screen is much smaller than the rest of the information, with no ability to pinch and zoom. This could be an issue for vision-impaired users.

**Comment by jmfield2** [comment]
related to #242 #202

**Comment by jailby** [comment]
The following is a screenshot of the fix:
![image](https://cloud.githubusercontent.com/assets/1370401/14643531/b7f7b798-061c-11e6-8bde-52583fbd39ce.png)

**Comment by barbeau** [comment]
Thanks!  Looks like something strange may be happening though with the time cutting into the pedestrian logo in the 2nd itinerary beginning time?  Also, have you looked on mobile?

**Comment by jailby** [comment]
Yes this is one of the problem I need to mention during the meeting. This PR fix the size of the time issue only to finish UCM milestone. I believe that after this PR we can contact them to tell them that we are done with the document they sent us.

However, by doing this change I noticed two issue that I want to talk about during the meeting (its my note in my previous comment).

Example of the problem from maps.usf.edu:
1) The size of the trip summary of the mode vary:
![image](https://cloud.githubusercontent.com/assets/1370401/14645401/817f1858-0623-11e6-9d90-4c95e24bf092.png)

2) The logo don't fit within their dedicated space:
![image](https://cloud.githubusercontent.com/assets/1370401/14645274/fe517020-0622-11e6-99a7-3482705a3ebf.png)

Screenshot on mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/14645532/0d0e0bd6-0624-11e6-9f34-96b1853b9536.png)

**Comment by jmfield2** [comment]
Fixed by acc6cbf
