### ISSUE TITLE
Parking lot data

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#240]
We received from the parking and transportation services:
[Coordinates for Lots2.xlsx](https://github.com/CUTR-at-USF/usf-mobullity/files/190647/Coordinates.for.Lots2.xlsx)

After a quick glance at it I noticed that the Lot 01 doesn't have the same coordinate in production and on the spreadsheet provided. 
Production: `28.060704 -82.412129` 
Screenshot of the location:
![image](https://cloud.githubusercontent.com/assets/1370401/14062156/64b967ac-f36b-11e5-936b-2da04180520a.png)

Spreadsheet:`28.060959, -82.411682`
Screenshot of the location:
![image](https://cloud.githubusercontent.com/assets/1370401/14062163/9d37008a-f36b-11e5-9c25-2619ebd043f4.png)

Also, as you can see the GPS coordinate given by parking and transportation services is neither the entrance nor the center of the parking lot.
I'm not sure how they determine what are the coordinate for a parking lot but since we are using them for routing people we need to be careful about it.

Our data on production seem more complete but there was a few that were on the spreadsheet but not coded. Only one item from the spreadsheet is not present in the code: Lot 10. 

Another thing is the parking lot at these coordinates: `28.060550 -82.418476` is called Lot 24B, on production, but in the spreadsheet the same parking lot has a different name 'Lot 24'. (The GPS coordinates are almost the same).

I made bold the two row concerned by the aforementioned problems in the xls document attached.

**Comment by barbeau** [comment]
Feel free to stick with our lat/long on production - we don't need to use their exact data.  I think Lot 24B is fine too, I believe we got that from a USF map.  I'd focus more on lots that exist in spreadsheet but not production, like Lot 10.  I think everything else is fine as-is.

**Comment by jailby** [comment]
Ok thanks.

Also, I wasn't sure of the milestone? Is it for Launch (We probably need to change the date)? 

I don't think we should mix in usf ucm.

**Comment by barbeau** [comment]
Not USF ucm, launch would work for now.

**Comment by jailby** [comment]
Data received from Donna Giammaresi.

More missing parking:
- [x] Lot Life Science Annex `28.061324 -82.417347` **(this is state vehicle only. This shouldn’t exist on your map.)**
- [x] Lot Lifsey - `28.055898 -82.411317` **(guest to the presidents house. This shouldn’t exist on your map.)**
- [x] Lot Sago Drive - `28.059499 -82.411515` **(departmental reserved only. This shouldn’t exist on your map.)**
- [x] Lot Varsity Tennis Court - `28.064334 -82.405806` **(Parking permit: E)**

**it is actually two separate lot:** 5A and Cedar Drive are two different areas. The entrance to 5A is right next to Cedar Drive though. Cedar drive has 4  EV- Electric Vehicle Spaces
- [x] 5A 28.064169, -82.412313
- [x] Lot Cedar Drive 28.064254, -82.412548
- [x] Lot 23B - Lot Intramural Field - `28.056086 -82.408083` **(call this Lot 23B)** 
- [x] Lot 11/12 - Lot Morsani Service Area - `28.067331 -82.419418` **(this shouldn’t be on your map)**

**Comment by jailby** [comment]
When a parking lot has two names both should be present as a single entry in the Geocoder.

However in the layer only the English designation should be used instead of the numbered designation.

We are also waiting on Donna to have more information about the last parking lot data.

**Comment by jmfield2** [comment]
http://www.openstreetmap.org/changeset/43752059
