### ISSUE TITLE
Blue light emergency phone marker position

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#243]
The marker of the blue light emergency phones are positioned in the center of the image used as a marker.

Since it is a 'buble' : 
![image](https://cloud.githubusercontent.com/assets/1370401/14113238/09fd52ec-f5a0-11e5-9b0d-ca9e5379eee3.png)

The position of the image on the map should be the image's bottom center.

It is not the case at the moment on production and it can lead to some confusion because of the scaling of the image depending on the zoom level.

Example:

Screenshot when the map is zoom out:
![image](https://cloud.githubusercontent.com/assets/1370401/14113336/8c891e6c-f5a0-11e5-9b40-dfee1b1976b9.png)

On the screenshot you can see the blue light pointed by the arrow seem on the south sidewalk of USF Alumni Dr. but in reality they are on the north sidewalk of USF Alumni Dr.

On this screenshot which is a more zoomed in view it is more clear that the blue light emergency phone are on the north side walk of the USF Alumni Dr.:
![image](https://cloud.githubusercontent.com/assets/1370401/14113453/07ccba66-f5a1-11e5-8b59-00fae75c42d9.png)

**Comment by jmfield2** [comment]
This should be fixed once my big poi PR is merged later today

**Comment by jailby** [comment]
Oh ok lol. :+1: 

I didn't notice it in the PR.

**Comment by jailby** [comment]
Fixed by 1ca422903259c905f547d1b55e0f04a989b0b8b2
