### ISSUE TITLE
Postal services and mailboxes (USPS/FedEx/UPS)

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#249]
Having information about postal services an mailbox on/around campus would be usefull.

First we need to find all the data available. There is some mailbox available on campus. Maybe some services on campus has a record of it.
I found the following link but I don't think the data is complete: http://www.mailboxmap.com/

Then, this data need to be added to OSM and/or the Geocoder. The way to add this data need to be discussed.

Finally if there is a sufficient amount of mailboxes and postal services on/around a layer could be dedicated for it.

The parent issue for POI can be found [here](https://github.com/CUTR-at-USF/usf-mobullity/issues/177).

**Comment by barbeau** [comment]
My opinion - we should add these to the Geocoder and OSM first, but should wait to add a mail map layer until we have a collapsible left layers panel.
