### ISSUE TITLE
Geocoder behavior with whitespace

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#257]
The problem is hard to explain so I recommend to directly look at the screenshots to see the difference and refer to the summary for more detailed explanation.

**Problem summary:** If a user enter _a part_ of a building name, e.g., "administration",  it will receive all entries that contain this _part_ in the geocoder. However, if the user add a space, e.g., "administration " at the end of this _part_ it will receive all entries not ending with this _part_.

This means that the string "Marshall Student Center " does not match the entry "(MSC) Marshall Student Center" because of the space at the end.

Some screenshots for example:
**The cursor in the start field is the important part. It will show you if there is a space at the end or not**
![image](https://cloud.githubusercontent.com/assets/1370401/14534609/f06d5e5e-0237-11e6-91af-4472d0a3901f.png)
![image](https://cloud.githubusercontent.com/assets/1370401/14534620/fb6dca64-0237-11e6-98e3-cbef20dad5c8.png)

Some more:
![image](https://cloud.githubusercontent.com/assets/1370401/14534678/337688e2-0238-11e6-970a-1fbe5464794e.png)
![image](https://cloud.githubusercontent.com/assets/1370401/14534686/3bbc4262-0238-11e6-9d52-5a2f69885f8e.png)

more:
![image](https://cloud.githubusercontent.com/assets/1370401/14534726/70cd7a02-0238-11e6-9f26-3ef5818cc949.png)
![image](https://cloud.githubusercontent.com/assets/1370401/14534737/77a3f6ee-0238-11e6-9379-94a0eff8ba5e.png)

This problem can occur when a user copy/paste a building name or if the user add a space as an habit after the last word.

**Comment by barbeau** [comment]
So I guess potential solutions would be to a) trim any whitespace before trying to match what the user entered, or b) add whitespace after the hard-coded entries.  a) seems like the better option.

Any other ideas?

**Comment by jmfield2** [comment]
I agree, the best way to fix this is probably to trim the input before it gets sent to the geocoder.  It would be nice to support selectively disabling this somehow like using "quotes" to still search for words including a trailing space, if that is what the user intended to do
