### ISSUE TITLE
Jquery error message in the console

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#264]
The following error message appear in the console:
![image](https://cloud.githubusercontent.com/assets/1370401/14790597/e419effe-0adf-11e6-91fc-b2464a03a82d.png)

text:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

This problem need to investigated.

**Comment by jmfield2** [comment]
Also, I noticed that I'm seeing this on my FF/Linux:

Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery-1.9.1.js:6208:12

Probably would be fixed by updating jquery.

**Comment by jmfield2** [comment]
Looks like the Synchronous XMLHttpRequest warning is from a few ajax calls where async: false in:

src/client/js/otp/core/TransitIndex.js
and 
src/client/js/otp/layers/BikeStationsLayer.js

Removing those fixes the warning; however, at least for TransitIndex.js, this will break some stop-related code.   Additional code rewriting might be necessary there.

It might also be a good time to take another look at pulling in updates from upstream:
https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/client/js/otp/core/TransitIndex.js

which appears to already have removed async ajax calls.

**Comment by jmfield2** [comment]
Turns out, upgrading jquery + jqueryui to the latest 1.x as of now breaks the jqueryui accordion widget used by the trip itinerary
