### ISSUE TITLE
Change to Mapbox for map tile provider

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#266]
The issue #223 as been investigated and the information about mapbox will be grouped in this issue.

Mapbox seem to be more powerful than mapquest (current tile provider). Also:
- **MapQuest** - Free plan - 15,000 transactions/month for free.  This includes both map tile requests and geocoding requests - we're currently using MapQuest for both.
- **Mapbox** - Standard plan (free for us via educational discount) - 100k map views or 75k mobile users / month, 5GB storage | 20 styles

Mapbox as a tool to create/modify/visualise a tile set:
https://www.mapbox.com/studio/

The map style can be exported in text file somewhat readable. This text file can be added to github to keep track of its version. 

The default style named "Streets" is the closest to what we want I believe.

The following is a list of elements that are missing from the style "Street":
- [x] **Abbreviations for the name of buildings**
  I sent an email to their technical support to figure out why the abbreviations were left out.
- [x] **Bollards**
  https://www.mapbox.com/help/overpass-turbo/#beyond-mapbox-streets-using-overpass-turbo **Important Note:** This will be static data which won't reflect any change in OSM. 
- [x] **Pedestrian area**
  https://www.mapbox.com/help/add-layer-studio/
  Adding the Pedestrian area can be tricky. When adding the layer select directly on the map a pedestrian area, then filter by adding class=pedestrian.
- [x] **Labels are too small (building/road)**
  The size of the label can be modify depending on the zoom level. Also, OSM data probably need to be modify to be more consistant. Indeed, some building label are directly associated with the building element in OSM and some are just markers on top of the building.
- [x] **Service roads (parking way, delivery etc..) are too similar to normal road.** These should be diminished. When selecting it don't select road with class=track
- [x] **Running track** select via road with class=track

The following map is the one created with the aforementioned issue fixed. I used strong color for each element selected to show them clearly.
https://api.mapbox.com/styles/v1/jailby/cin8wzt270008adnp6oqve9f6.html?title=true&access_token=pk.eyJ1IjoiamFpbGJ5IiwiYSI6ImNpbjh3YXA1bDFqOGh1ZGtzcXlrajV3cGQifQ.8c78IvXfNkZDU56XbQ3f-Q#14.999737608879524/28.06169205947684/-82.41497305054254/0

The following is a list of additional elements that are present in the style "Street":
- **POI food services are present for example starbuck** OSM doesn't have a complet list of them thus if we want to include them we should update OSM first.

**Comment by jailby** [comment]
I found a way to add bollards as a new layer without making it static data:

In the json file of the mapbox style "street" you can find the following attribute:

```
"1444856931506.5164": {
    "name": "Barriers",
    "collapsed": true
    }
```

With some reverse engineering (basically looking how the rest of the attribute work) I understood that I could do the following:

```
{
            "id": "bollard",
            "metadata": {
                "mapbox:group": "1444856931506.5164"
            },
            "source": "composite",
            "type": "circle",
            "source-layer": "Barriers",
            "interactive": true,
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "circle-color": "hsl(247, 85%, 47%)"
            }
        }
```

I took me a while but that piece add the bollard to the mapbox style.

The bollard won't be visible yet though. To make them visible we need to add them as a layers similarly to the pedestrian area:
https://www.mapbox.com/help/add-layer-studio/

**Comment by jailby** [comment]
The following is the url of the map style I made:
https://api.mapbox.com/styles/v1/jailby/cinvtn1en001cb9kru3whf9l8.html?title=true&access_token=pk.eyJ1IjoiamFpbGJ5IiwiYSI6ImNpbjh3YXA1bDFqOGh1ZGtzcXlrajV3cGQifQ.8c78IvXfNkZDU56XbQ3f-Q#16.883501385281207/28.05956878932477/-82.41593963444424/0

I believe that the building should be a darker gray and the pedestrian area should be a lighter gray.
Also the opacity of building after a zoom level is set to zero. It should not because it only shows the contour of the building and does not look good.

When integrating a custom map style from mapbox as follow:

```
name: 'Map',
            tileUrl: 'https://api.mapbox.com/styles/v1/jailby/cinvtn1en001cb9kru3whf9l8/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiamFpbGJ5IiwiYSI6ImNpbjh3YXA1bDFqOGh1ZGtzcXlrajV3cGQifQ.8c78IvXfNkZDU56XbQ3f-Q',
            attribution : 'Data, imagery and map information provided by <a href="http://www.mapbox.com" target="_blank">Mapbox</a>, <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors.'
        },
```

If zoomed too much the tile rendering is not correct. I don't know the reason of this problem. We could contact their technical support to ask assistance about it if we can't figure out.
https://www.mapbox.com/contact/

About the abbreviation of the Building in between parentheses the following is the discussion with the technical support of mapbox.
For now we will retrieve building name with their abbreviation through overpass and delete any other label from the map style.
@barbeau  has been cc'ed on this discussion

> Hello,
> 
> Thanks for the information, how do you plan to address this issue? Will you restore the parentheses? Or will there be an option to add or not the parentheses?
> 
> Best regards,
> Jean-Baptiste Subils
> 
> 2016-05-06 12:33 GMT-04:00 Rafa Gutierrez help@mapbox.com:
> Hello,
> Yes we found that we had to remove parenthesized text from all labels because of inconsistencies such as use of nicknames or alternative names. It's on the table to address but for now, we recommend using a custom source for names to show abbreviations. Tools such as Overpass Turbo are handy in this instance. Please let me know if this helps or if you have questions.
> 
> Best,
> Rafa
> 
> How would you rate the quality of my reply?
> Awesome!   Acceptable   Not so swell
> 
> ## 
> 
> Rafa Gutierrez
> help@mapbox.com
> Please see our Help page to learn more about Mapbox.
> {#HS:197062981-62379#}

**Comment by barbeau** [comment]
Mapbox just announced today via email that they've restyled their main map layers - we should check these out and see if we want to base our tiles off of the new Streets style.

> Hey there,
> Today we are relaunching all of our maps. Check out the new design and start building your mobile and web apps.
> Streets
> A comprehensive, general-purpose map that emphasizes accurate, legible styling of road and transit networks.
> 
> Start building with Streets
> Outdoors
> A general-purpose map with curated datasets and styling tailored to hiking, biking, and adventuring.

https://www.mapbox.com/maps/streets/?utm_source=styles_launch&utm_medium=email&utm_content=streets_image&utm_campaign=styles_launch

> Start building with Outdoors

Satellite Streets
A comprehensive set of road, label, and POI information brings clarity and context to the crisp detail in our high-resolution satellite imagery.

https://www.mapbox.com/maps/outdoors/?utm_source=styles_launch&utm_medium=email&utm_content=outdoors_image&utm_campaign=styles_launch

> Start building with Satellite Streets
> 
> Light & Dark
> Subtle, full-featured maps designed to provide geographic context while highlighting your custom data.

https://www.mapbox.com/maps/light-dark/?utm_source=styles_launch&utm_medium=email&utm_content=light_image&utm_campaign=styles_launch

> Start building with Light & Dark
> Happy mapping!
> 
> Love,
> Your friends at Mapbox

**Comment by barbeau** [comment]
Here's a tutorial from Mapbox showing how to add a POI layer using studio:
https://www.mapbox.com/blog/custom-poi-layer-in-studio/

However, I believe this is just for static content that is manually added - it's not for dynamic content pulled from OpenStreetMap, which is what we want for most layers (with the exception of the blue lights).  But I still wanted to capture this link in this thread in case it proves useful later.
