### ISSUE TITLE
Change font for Layers box and MoBullity title

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#27]
The current font for MoBullity title and Layers box looks like a stencil and IMHO is not very readable:

![image](https://cloud.githubusercontent.com/assets/928045/6583825/28869c42-c73d-11e4-895e-1e13ab1e12ab.png)

@jmfield2 Could you please look at changing this font to something a bit more traditional?  Sans serif, from my understanding, is generally easier to read/understand.

**Comment by jmfield2** [comment]
Hm. I see that the font-family is still stencil for the layer information like the mobullity header ... but it looks different on my end:

![image](https://cloud.githubusercontent.com/assets/3628509/6632476/467ace90-c90d-11e4-87c9-9d04b08c0f06.png)

**Comment by barbeau** [comment]
My screenshot was from Chrome.  IIRC the different browsers have different
font sets, and they default to others if the specified font isn't included.

**Comment by jmfield2** [comment]
I believe this is fixed, can someone else check it?

**Comment by barbeau** [comment]
This is what I currently see on Chrome on Windows:

![image](https://cloud.githubusercontent.com/assets/928045/8619376/aa3035da-26e4-11e5-9f34-40cc9870056c.png)

**Comment by jmfield2** [comment]
From your last screenshot, my layers seems to look the same.  The font-family for that (and the top links) is: 'Helvetica Neue', Arial, Helvetica, sans-serif

Should we go ahead and update the old stencil font for mobullity (defined at src/client/style.css:376  - #site-title a) to that, or something else?

**Comment by barbeau** [comment]
Sounds good!
