### ISSUE TITLE
Add "avoid stairs" trip option back into UI

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#28]
I think this option, formerly called "wheelchair accessible", was removed by default a while back in the main OTP Leaflet UI, and we never added it back in.

See the old OTP UI for an example:
http://opentripplanner.usf.edu/ 

I believe this is simply turned on with “&wheelchair=true” parameter.  I think "avoid stairs" is probably the best user-facing description for this, since it primarily does this, and there is a lot more that goes into accessibility than just stairs.

@jmfield2 could you please re-add this to the UI and push to the site?

**Comment by jmfield2** [comment]
This is fixed on mobullity now. Adding a test case to ensure it stays on the trip planning form
