### ISSUE TITLE
Car Routing

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#288]
The version of OpenTripPlanner we are using has several known issues with car routing.  Upstream/later versions seem to have improvements in this area.

Specifically, if you route from CHG to CGS via Car, the trip plan will fail.

![screenshot from 2016-06-21 08 43 10](https://cloud.githubusercontent.com/assets/3628509/16229782/4a2ba84a-378c-11e6-907d-a4349bda8450.png)

**Comment by jmfield2** [comment]
From the meeting Friday, we found this post on the group:
https://groups.google.com/forum/#!msg/opentripplanner-dev/p8mp7p2-I0U/h6ZBjOi_fUgJ

Which suggests this might be related to an inappropriate oneway tag, where the roundabout should instead be:
junction=roundabout

**Comment by barbeau** [comment]
There is a roundabout in front of the Lifsey House (PRS) that doesn't have
the routing problem, and that way doesn't have any tags on it - so it does
appear that the oneway tag has something to do with the problem.

**Comment by jmfield2** [comment]
So, replacing the oneway tag with junction=roundabout does not seem to fix the issue, but adding the roundabout tag to the lifsey roundabout does not seem to break routing there like it does here.  Even adding oneway=yes to lifsey doesn't break the routing

Reversing the route (starting at CGS and ending elsewhere) does work.

Also, removing both the oneway tag and roundabout tag fixes the issue, though it routes the wrong way.

Another idea I thought might be an issue is the ordering of nodes causing OTP to be confused about the direction of traffic ... with lifsey, the start/end node order is the junction at the top.  With CGS, the way begins with one node to the left/west of the top junction..

**Comment by jmfield2** [comment]
Confirm that reordering the nodes for the way fixes the issue w/o touching the oneway tag, and allows routing the correct way around the circle.

I'll commit the changes to OSM and reupload to chef to trigger a rebuild shortly

**Comment by jmfield2** [comment]
Updated OSM @ http://www.openstreetmap.org/changeset/40407931

**Comment by jmfield2** [comment]
Uploaded new tampa extract with this change to chef, and confirm the issue with CGS is fixed on mobullity
