### ISSUE TITLE
OSM Data Issues

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#29]
This issue is for on-going issues related to OSM data.

Fixed today:
Remove one-way tag for way near Laurel Garage that doesn't seem to be one-way at all and which Google considers two-ways.  http://www.openstreetmap.org/changeset/30691603

**Comment by jmfield2** [comment]
Remove one-way for entrance to Greek Housing: http://www.openstreetmap.org/changeset/30924810

**Comment by barbeau** [comment]
@jmfield2 I think we can close this issue, right?  We're now tracking OSM issues in individual issues here, so this umbrella one can be closed.

**Comment by jmfield2** [comment]
That sounds about right to me - I'll close it
