### ISSUE TITLE
Remove Life Sciences building (LIF) from map.osm data

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/usf-mobullity#299]
Life Sciences building does not exist anymore. We might need to remove it from map.osm data.

**Comment by jmfield2** [comment]
For reference, mohan's OSM changeset is uploaded @ 
http://www.openstreetmap.org/changeset/41352929

I noticed that the LIF building is still on the 'official' JPG maps... So, I'm not sure why or if we should also reflect that too even though it doesn't currently exist.

**Comment by barbeau** [comment]
I'd go with what's actually true based on our observation.  USF jpg map is
likely outdated.
