### ISSUE TITLE
Allow users to vote on new features

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#302]
I imagine as USF Maps becomes more widely used, we're going to get a lot of suggestions for new features.  It would be great to be able to harness an existing tool to let users vote on new features instead of manually managing this.

We’ve successfully used Ideascale and their free tier in the past for the OneBusAway project:
http://onebusaway.ideascale.com/

So that's one option.  I've reached out to USF IT to see if they have any other solutions.

**Comment by jmfield2** [comment]
I always think of uservoice for things like this, but it seems they no longer offer a free plan.

Another option from a quick google might be:
http://feathub.com/docs

which is helpful because it is based on github issues, and is free for open source projects

**Comment by barbeau** [comment]
I created a FeatHub account for this repo here:
http://feathub.com/CUTR-at-USF/usf-mobullity
