### ISSUE TITLE
Pedestrian area not connected

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#32]
### Problem:

A pedestrian area corner not connected with a way in Mobullity.
However, it is actually connected in OSM.

Example of the trip:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.060865862609578%2C-82.41122871637344&toPlace=28.060619703586344%2C-82.4114191532135&time=3%3A59pm&date=06-26-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&bannedRoutes=undefined&showIntermediateStops=true&itinIndex=0

Here is a screenshot of this trip:
![image](https://cloud.githubusercontent.com/assets/1370401/9390704/b5df272a-4740-11e5-9bd7-1a5fc3213322.png)

And the following is the raw graph, showing that one of the three edge is not connected to the others:
(More zoomed in that the previous screenshot and center on the way to see it better)
![image](https://cloud.githubusercontent.com/assets/1370401/9390760/20065650-4741-11e5-9373-7067e242942e.png)

Example of when it actually work:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.061121488690844%2C-82.41131722927094&toPlace=28.060619703586344%2C-82.4114191532135&time=3%3A59pm&date=06-26-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&bannedRoutes=undefined&showIntermediateStops=true&itinIndex=0

**Comment by jailby** [comment]
Related issue created on the official OTP repository 
https://github.com/opentripplanner/OpenTripPlanner/issues/2111

**Comment by jailby** [comment]
A fix has been provided in the [issue](https://github.com/opentripplanner/OpenTripPlanner/issues/2111#issuecomment-137046621) of the Official OTP which is [here](https://github.com/buma/OpenTripPlanner-Maribor/commit/664fbfb3cd06dc6245bbe8d2cb1dba83e2692476).

What is the procedure to apply the changes? 
Should I just modify the file "WalkableAreaBuilder.java" to mirror the changes?

**Comment by jmfield2** [comment]
If you still need to know about this, yes I think all you need to do is try to mirror the changes.

**Comment by jailby** [comment]
I didn't found the file "WalkableAreaBuilder.java" in our repository.

I would assume it come from the fact we are a little behind from the current version of otp and this part of the graph builder got its own file on a later version.

I know you @jmfield2 were updating our repository lately, thus I don't know if we should wait until you are done.

**Comment by jailby** [comment]
The [code modified](https://github.com/buma/OpenTripPlanner-Maribor/commit/664fbfb3cd06dc6245bbe8d2cb1dba83e2692476) by Buma need tp be added at the following location:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/main/java/org/opentripplanner/graph_builder/impl/osm/OpenStreetMapGraphBuilderImpl.java#L1028

**Comment by jmfield2** [comment]
![issue32](https://cloud.githubusercontent.com/assets/3628509/10092250/4c855a86-6312-11e5-88bb-03539294843b.png)

The upstream patch fixes this issue.
