### ISSUE TITLE
Viewing itinerary link doesn't fully contain trip path on map

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#327]
Currently, when clicking on an itinerary link such as:
https://maps.usf.edu/?module=planner&fromPlace=(CUTR)%20Center%20for%20Urban%20Transportation%20Research%3A%3A28.0586%2C-82.4161&toPlace=28.050555103935533%2C-82.41532444953918&time=9%3A45am&date=08-25-2016&mode=TRANSIT%2CWALK&maxWalkDistance=482.8032&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0

...the map view will currently center on the itinerary if the user has NOT permitted it (it should also center on it when the user HAS permitted it, but that's currently a bug documented in #326).

However, the origin is cut off and hidden behind the top green banner:

![image](https://cloud.githubusercontent.com/assets/928045/17971841/79ae0eea-6aaa-11e6-9c03-b1cb9d5bfe69.png)

The origin should be visible within the map bounds.  I would also suggest we show a bit more of the map surrounding the origin and destination (i.e., add more padding between origin and destination and screen edge).

Reproduced on Firefox on Windows 7 Enterprise.

**Comment by jmfield2** [comment]
The following link has the same issue in firefox and chrome:
https://maps.usf.edu/?module=planner&fromPlace=28.055412361385066%2C-82.40432739257812&toPlace=28.050555103935533%2C-82.41532444953918&time=9%3A45am&date=08-25-2016&mode=TRANSIT%2CWALK&maxWalkDistance=482.8032&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0
