### ISSUE TITLE
SOC building marker

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#329]
The SOC building GPS coordinates are close to the back entrances and not the main entrance.
This result in the trip planner going around the building instead to the main entrance (see screenshot/trip link).

To solve easily this problem the GPS coordinate can be change to be closer to the main entrance.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1370401/17973470/997d5fe0-6ab0-11e6-990e-712640e3490f.png)
Link to the itinerary:
https://maps.usf.edu/?module=planner&fromPlace=(SOC)%20Social%20Science%20Building%3A%3A28.0615%2C-82.4092&toPlace=(ENB)%20Engineering%20Building%20II%3A%3A28.0587%2C-82.4152&time=10%3A35am&date=08-25-2016&mode=TRANSIT%2CWALK&maxWalkDistance=482.8032&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0

Note: this problem was present with the REC building and may be present for other buildings too

**Comment by barbeau** [comment]
Thanks for letting us know @jailby!

**Comment by mohangandhiGH** [comment]
Hi @jailby. To confirm the main entrance of SOC building, I have added a screen shot below. Can you please have a look and comment.

![image](https://cloud.githubusercontent.com/assets/17164961/18099906/b2c6f48e-6eb6-11e6-8f99-4846e9b80bf4.png)

**Comment by jmfield2** [comment]
fixed by 3cb84df2f0e456016fb358f894126b869923b4b7
