### ISSUE TITLE
Auto-appending #layers or #tripplanner to URL is broken

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#342]
Looks like at some point recently both production and mobullity are no longer adding the "#layers" or "#tripplanner" to the URL when these items are selected in the menu.

Steps to reproduce:
1. Tap on menu
2. Tap on Layers (or Trip Planner)

What I expect:

"#layers" should be appended to the URL to be https://maps.usf.edu/#layers

What I see:

Nothing gets appended to the URL

Reproduced in Chrome on Windows 7 Enterprise.

**Comment by mohangandhiGH** [comment]
In the issue #303, we are updating URL based on start marker, end marker and trip plans.
These #trip and #layers are appended at the end of URL when we open trip/layers widget  also after markers/planned trip are present.
For eg:
https://localhost:8444/?module=planner&fromPlace=28.060193657790776%2C-82.414584159851070#layers
So, while committing that issue, the code related to these appending's is deleted.

**Comment by barbeau** [comment]
@mohangandhiGH thanks for tracking down the problem!

**Comment by jmfield2** [comment]
fixed by fff2d4ac6b38142de06f83a692a6c5cab9ba78ad
