### ISSUE TITLE
Add OccupancyStatus % progress bar

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#345]
Now that we have the occupancy statuses mapped from #328, we would like to use those and display a "progress bar" indicating the % full similar to how it is shown currently on usfbullrunner.com:

![image](https://cloud.githubusercontent.com/assets/928045/17973214/8de33e58-6aaf-11e6-8847-08ebab4f04ea.png)

The possible values and % mappings are defined in the gtfs-realtime generator and are:

https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/blob/master/src/main/java/edu/usf/cutr/gtfs_realtime/bullrunner/GtfsRealtimeProviderImpl.java:

VehiclePosition.OccupancyStatus.EMPTY  <= 0

VehiclePosition.OccupancyStatus.MANY_SEATS_AVAILABLE <= 50

VehiclePosition.OccupancyStatus.FEW_SEATS_AVAILABLE  <= 70

VehiclePosition.OccupancyStatus.STANDING_ROOM_ONLY <= 90

VehiclePosition.OccupancyStatus.CRUSHED_STANDING_ROOM_ONLY (> 90 and < 95)

VehiclePosition.OccupancyStatus.FULL >= 95

Also see the GTFS specification:
https://developers.google.com/transit/gtfs-realtime/reference/OccupancyStatus-vp

**Comment by jmfield2** [comment]
empty, many green
few = yellow
standing+ = red

**Comment by jmfield2** [comment]
Here are some screenshots of the progress bar in #355 for reference:

Standing:
![occupancy_standing](https://cloud.githubusercontent.com/assets/3628509/18992380/fa8cb964-86eb-11e6-8435-1202162cc195.png)

Few seats:
![occupancy_few](https://cloud.githubusercontent.com/assets/3628509/18992378/f78de544-86eb-11e6-84c1-2e4e4d9ade41.png)

Many seats:
![occupancy_many](https://cloud.githubusercontent.com/assets/3628509/18992377/f3f2091a-86eb-11e6-96ff-e4b912c4160e.png)

Empty:
![occupancy_empty](https://cloud.githubusercontent.com/assets/3628509/18992375/eff143b2-86eb-11e6-8b60-aae80dc5d71e.png)

(Not pictured, Crushed standing, and full - both are red, and 92, 95% respectively)

**Comment by barbeau** [comment]
Looks good!
