### ISSUE TITLE
Layers Category - Help

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#366]
Proposal to add a new category to the layers widget (with collapsible sections) called:

Help
- [x] Blue Light Emergency Phones
- [x] "Info Kiosks" which should include both smart and non-smart boards in and around campus.  The OSM tag for this appears to be: tourism=information

**Comment by barbeau** [comment]
I think we should emphasize the "smart" kiosk locations, either through different marker indicator or at least within the popup balloon when tapping on the marker.

**Comment by jmfield2** [comment]
Note the smart kiosks appear to be from the ["x2omedia"](http://x2omedia.com) vendor based on observations of their setup (windows username).
