### ISSUE TITLE
Change "Empty" Occupancy Status vehicle marker UI

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#368]
Here are a few examples of how we show occupancy in vehicle markers:

![image](https://cloud.githubusercontent.com/assets/928045/19982463/997d31ec-a1dc-11e6-8277-134e400da7cc.png)

The "Empty" indicator seems a little confusing to me - I would expect that if it's empty, there is no bar.  Instead we show roughly 20% full.

Let's discuss in Friday's meeting.

**Comment by barbeau** [comment]
Similarly, looking at this more I'd expect "many" seats to be over 50% empty.

**Comment by jmfield2** [comment]
For reference, these values are defined in https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/layers/BusPositionsLayer.js#L176 

EMPTY = 25%
MANY = 50%
FEW = 75%
STANDING = 90%
CRUSHED = 92%
FULL = 95%

and 

https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/blob/master/src/main/java/edu/usf/cutr/gtfs_realtime/bullrunner/GtfsRealtimeProviderImpl.java#L465

0 = EMPTY
1-49 = MANY
51-70 = FEW
71-90 = STANDING
91-95 = FULL
96+ = CRUSHED (perhaps full and crushed should be reversed?)
