### ISSUE TITLE
HART bus stops layer doesn't work

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#37]
On http://mobullity.forest.usf.edu/index.html, I no longer see the HART bus stops when turning on the "HART" layer:

![image](https://cloud.githubusercontent.com/assets/928045/8883688/b8ffa81c-321e-11e5-8f55-70a4ba4e3ab1.png)

**Comment by barbeau** [comment]
@jmfield2 Is this just because we're missing HART GTFS data in OTP?

I can't seem to plan a trip on HART either.  Here's their newest GTFS data:
http://www.gohart.org/google/google_transit.zip

**Comment by jmfield2** [comment]
see PR #57
