### ISSUE TITLE
Collapsing Layers menu is cut off when expanded on mobile

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#371]
Below screenshots are from an LG G5 w/ Android 6.0.1 and mobullity.forest.usf.edu

When the collapsing Layers menu is expanded, the bottom of the menu is cut off (i.e., cascades off the white part), and the window contents aren't scrollable (I believe the previous menu was scrollable on smaller screens).

![image](https://cloud.githubusercontent.com/assets/928045/20073299/af883b6a-a4f9-11e6-9713-191904109d1a.png)

**Comment by jmfield2** [comment]
Adding overflow: scroll to the CSS here seems to fix this, and I think it looks good on mobile (the scrollbar is hidden until the user tries to scroll and then it is a small gray line), but this adds a space on the right side next to the chevron on desktop (firefox) even when there is nothing to scroll.

I can PR that fix now, and we can work on a better fix for desktop later if that sounds OK.  One idea might be to try and detect when the height is taller than the available area (on expansion) and enable the scrollbar then, and disable it whenever the height is sufficient..

**Comment by barbeau** [comment]
Yeah, that works for me.
