### ISSUE TITLE
Allow linking to particular layers being active

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#382]
**Summary:** 

I'd like to be able to send someone a link that controls which layers are actively shown on the map when they click on the link.

For example, to have the Parking Lots layer be automatically enabled and visible, a sample link would be https://maps.usf.edu/#layers?parking%20lots=enabled

**Steps to reproduce:** 

Copy/paste link when layers are checked

**Expected behavior:** 

Included the state of whether layers are enabled (i.e., visible) or not

**Observed behavior:** 

All layers are always disabled (i.e., not visible) when clicking on https://maps.usf.edu/#layers.

**Platform:** 

Windows 7 Enterprise w/ Chrome

**Comment by jmfield2** [comment]
I implemented this using a BackboneJS router to track the URL fragments which look like:
http://localhost:8000/#layers/parkinglots,carshare

I'll demo it at the meeting today
