### ISSUE TITLE
Usf Maps page does not load

### ISSUE THREAD

**Issue by Suryakandukoori** [CUTR-at-USF/usf-mobullity#406]
**Summary:** 

USF maps page does not load.

**Steps to reproduce:** 

Enter URL https://maps.usf.edu/ in IE 11 and enter the page.

**Expected behavior:** 

The USF Maps page opens with full working functionality.

**Observed behavior:** 

The page does not seem to load using IE version 11.1198; the only portion that will load is the top green banner with the page layers option.

**Platform:** 

 IE version 11.1198

**Comment by Suryakandukoori** [comment]
![image007](https://cloud.githubusercontent.com/assets/28587713/26609860/c40bde70-4558-11e7-9eec-195823260123.png)

**Comment by barbeau** [comment]
This was reported by USF PATS, but so far we can't reproduce, so I'm closing as "won't fix". If we get more info to reproduce we will reopen.
