### ISSUE TITLE
One way restriction not respected

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#42]
The following shouldn't happen:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.06904559564242%2C-82.40837752819061&toPlace=28.069253867752828%2C-82.40851163864136&time=2%3A40pm&date=08-07-2015&mode=CAR&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&bannedRoutes=undefined&showIntermediateStops=true&itinIndex=0

There is a one way restriction:
http://www.openstreetmap.org/way/38521249

**Comment by barbeau** [comment]
Thanks @jailby!  Can you please add this to the unit test list too?

**Comment by jailby** [comment]
It is already on there.

**Comment by jailby** [comment]
This trip was taking the one way lane from Fletcher Ave. onto USF Maple Dr. for both car and pedestrian.

It has been fixed by adding the tag (One way and U-turn restriction) in OSM.
