### ISSUE TITLE
Change header design - use USF horizontal logo, get rid of MoBullity, add hamburger menu

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#46]
More suggestions from USF IT - we should change the header of the app so that it looks closer in appearance to the main MyUSF app:

![image](https://cloud.githubusercontent.com/assets/928045/9227305/c9d902d4-40e0-11e5-9cbe-324efcbc5220.png)

This involves removing the MoBullity name, and replacing it with the horizontal gold USF logo - I asked USF IT to provide the one they are using in MyUSF.

They also want us to use a hamburger menu to access the Trip Planner and Layers functionality, instead of the current tabs.  Here's a quick mockup of what that might look like:

![image](https://cloud.githubusercontent.com/assets/928045/9227609/78b529a8-40e2-11e5-89e1-0a460595c48c.png)

...and maybe a panel on the side with the options?  Open to ideas here.

Additionally, we should use the exact green and gold colors specified by the USF design guides:
http://usfweb4.usf.edu/ucm/marketing/colors.aspx

**Comment by barbeau** [comment]
If we don't hear back from USF IT, let's use the solid gold horizontal logo in bottom left corner from the official USF logo page:
http://usfweb4.usf.edu/ucm/marketing/logos/logo-download.aspx

**Comment by jailby** [comment]
Note: the [welcome popup](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/modules/planner/PlannerModule.js#L144) need to be update to reflect this change

**Comment by jailby** [comment]
The following  framerwork can be usefull:
http://materializecss.com/mobile.html

Edit: I tried this framework and it causes the trip planner widget to be not usable. 
![image](https://cloud.githubusercontent.com/assets/1370401/10434669/0a1190c2-70e9-11e5-9e3b-9294295fbac6.png)

If we go forward with this framerwork we might have to redo the trip planner widget.

**Comment by jailby** [comment]
This other framerwork could also be useful:
http://www.getmdl.io/index.html

**Comment by jailby** [comment]
This other framerwork is also an option:
http://jqueryui.com/

**Comment by jmfield2** [comment]
Hm the one I found was jquerymobile

**Comment by jmfield2** [comment]
There's also this:

http://www.jqueryscript.net/menu/Multi-functional-jQuery-Off-canvas-Navigation-Plugin-Sidy-js.html

And probably others..

**Comment by barbeau** [comment]
I'm splitting out the official USF colors item mentioned in the first comment to its own issue https://github.com/CUTR-at-USF/usf-mobullity/issues/107, as we already have the logo updated in https://github.com/CUTR-at-USF/usf-mobullity/pull/106#issuecomment-151530961.

**Comment by jailby** [comment]
This issue has been broken down in smaller issues. Some are fixed and other are in progress.

There is no need for this issue to still be open.
