### ISSUE TITLE
Trip going through delivery way

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#51]
The following trip is not supposed to go through the delivery way of the Sun Dom:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.058697750290175%2C-82.40580797195435&toPlace=28.059656364296405%2C-82.40605473518372&time=9%3A09am&date=08-14-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&bannedRoutes=undefined&showIntermediateStops=true&itinIndex=0

![image](https://cloud.githubusercontent.com/assets/1370401/9274579/1030f810-4265-11e5-86d1-752ea9517be8.png)

Link to the delivery way:
http://www.openstreetmap.org/way/45182297

**Comment by jmfield2** [comment]
So far, I don't see any reference to the 'access' tag restricting permissions on a way within the OTP graph_builder, and highway=service currently sets StreetTraversalPermission.ALL (which includes pedestrian).

Perhaps we should ask on the dev lists for advice on whether the highway=service should only allow driving modes, to use a different highway tag that will only permit driving (looks to be 4: trunk_link, motorway_link, trunk, and motorway), or something else.

The permissions are defined primarily by:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/main/java/org/opentripplanner/graph_builder/impl/osm/DefaultWayPropertySetSource.java

**Comment by jmfield2** [comment]
There was a related issue awhile back where OTP would sometimes route pedestrians on roads instead  is somewhat related, and I 'fixed' it on my local repo here:
https://github.com/jmfield2/usf-mobullity/blob/34324b69427c5b46bff3f98004c455d6c6bf33de/src/main/java/org/opentripplanner/graph_builder/impl/osm/DefaultWayPropertySetSource.java

This isn't yet in mobullity - I think it may need some additional tests to make sure it doesn't break everything - but it seems possible something like it could also be used to fix this.

**Comment by jmfield2** [comment]
Actually, it will try:
openstreetmap model OSMWithTags - way.isGeneralAccessDenied

but:
   // There are exceptions.
                return (way.isMotorcarExplicitlyAllowed() || way.isBicycleExplicitlyAllowed() ||
                        way.isPedestrianExplicitlyAllowed());

which all of them should be false since only highway=service is set

**Comment by jmfield2** [comment]
This seems to be fixed now.  In addition, the itinerary link above does not work because of the bannedRoutes=undefined parameter (subsequent links do not include undefined parameters, this was fixed as another issue)

Corrected link:
https://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.058697750290175%2C-82.40580797195435&toPlace=28.059656364296405%2C-82.40605473518372&time=9%3A09am&date=08-14-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0
