### ISSUE TITLE
Allow inputting full name for location for origin and destination

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#52]
When the user is planning a trip, it would be good if the user could search by building name instead of only by abbreviation.

Currently if a user start writing "eng" for "engineering" to plan a trip to either engineering buildings (ENC, ENB, ENA etc...) the user will only see "ENG" in the drop down box. 

Some full name of building are present in the drop down list of the Start/End boxes.

**Comment by jmfield2** [comment]
Fixed by c341c05009a62a03f4e86cb03f39b3b10ec4d3be
