### ISSUE TITLE
Going through parking lots

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#53]
Currently it is not possible to go through parking lot for a pedestrian.

In the following trip the user has to go around the Sun Dome when he actually could go through the parking lot:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.05948357771206%2C-82.40761578083038&toPlace=28.05986465460419%2C-82.40776866674422&time=1%3A57pm&date=08-17-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&bannedRoutes=undefined&showIntermediateStops=true&itinIndex=0

![image](https://cloud.githubusercontent.com/assets/1370401/9312391/5dd67a40-44ea-11e5-88e4-04e736173875.png)

**Comment by barbeau** [comment]
IIRC, whether or not we want to route pedestrians through parking lots was debated.  I believe we determined that we would only provide pedestrian routes through parking lots if there was an actual pedestrian path (e.g., sidewalk) there, due to safety reasons.

@jmfield2 Is this correct?

**Comment by jmfield2** [comment]
Sounds right

**Comment by barbeau** [comment]
I'm going to close this as "wont fix", because for now we're avoiding parking lots as a policy.  If this changes in the future we can re-open the ticket.
