### ISSUE TITLE
Add more USF-centric Points-of-Interest

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#63]
Here's the current official USF PDF map for visitors:
http://www.usf.edu/administrative-services/parking/documents/visitormap.pdf

And here are screenshots, in case the above link breaks:

![image](https://cloud.githubusercontent.com/assets/928045/9473293/12129654-4b28-11e5-9b7b-ca38f03e5e4a.png)

![image](https://cloud.githubusercontent.com/assets/928045/9473305/28dfd05e-4b28-11e5-8874-d4889029b131.png)

We should consider adding the places from the 2nd image as geocoded locations in MoBullity.  See https://github.com/CUTR-at-USF/usf-mobullity/issues/55 for how this is implemented.

There are also some items from the first map, like the "Electric Car Charging Station", that we may want to include in some manner.

**Comment by barbeau** [comment]
For restaurants on campus that have more than one location, like Subway and Starbucks, we should add the building name/abbreviation they are located in after the name.  For example, Subway locations could be:
- Subway (Marshall Student Center (MSC))
- Subway (Cooper Hall (CPR))

We could also consider having another layer for restaurants that shows these locations with markers on the map.

**Comment by jailby** [comment]
Fields and Stadiums would be a good thing to add too.
For example:
Magnolia Fields (not present yet)
Corbett Stadium (already present abbreviation: SPS)

**Comment by jailby** [comment]
This issue has been reported in a more global issue about the layers. #177 
Also, an issue about the food services has been created. #178 

Therefore I am closing this issue.
