### ISSUE TITLE
Remove requirement for "/index.html" in URL

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#64]
Right now, to see the site you have to enter the full URL into your browser, including the "/index.html":
http://mobullity.forest.usf.edu/index.html

If you don't add "/index.html", you just see a blank screen (see below for screenshot):
http://mobullity.forest.usf.edu/

We should allow the user to input just the main URL, and not require the "/index.html".  I believe this can be accomplished several ways.

@jmfield2 what's the best way to accomplish this, in your opinion?

![image](https://cloud.githubusercontent.com/assets/928045/9500422/61f67278-4bf3-11e5-8f5d-3b3cfd183dd0.png)

**Comment by jmfield2** [comment]
Since it is fixed upstream, but rebasing is hard maybe its best to try and
back port their fix for this? I'll take a look and try to do this if it
isn't too involved which I don't anticipate

**Comment by barbeau** [comment]
Ok, cool!  Let us know what you find.

**Comment by jailby** [comment]
You will have to revert the following commit (Or just modify accordingly):
https://github.com/CUTR-at-USF/usf-mobullity/commit/26f100cbd62df7d07a10565a48dabf99789fa218

**Comment by jmfield2** [comment]
Fixed by ece250a
