### ISSUE TITLE
User maximum zoom-in level not working

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#69]
Currently the user can zoom-in until the level 8:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L73

This cause a bug which cause the tile to all appear gray (no relevant screenshot).

I made some test and it appear to me that only the level 8 has this problem. Thus, I'm proposing to change the "minZoom" attribute to 9.
The fix is on the way.

**Comment by jailby** [comment]
This problem behave very differently depending on the computer and browser used. The problem probably come from the tiles rendering that requires too much resources for some computer.

**Comment by barbeau** [comment]
@jailby I don't think its a computational resource issue - I'm able to reproduce this in Chrome on my work machine which is a dual CPU Xeon w/ 16GB of RAM.  My feeling is that its a bug in the tile rendering code - I think that's [Leaflet](https://github.com/CUTR-at-USF/usf-mobullity/tree/mobullityrebase/src/client/js/lib/leaflet) for us?  Leaflet might be using OpenLayers or something else internally.  You might want to see if there is an updated version of Leaflet available via [their site](http://leafletjs.com/), and if that might fix the problem.

**Comment by jailby** [comment]
Ok good to know. 

I made this assumption because it was easier to reproduce on the desktop computer that is less powerful than my laptop.

**Comment by jailby** [comment]
To reproduce this bug:
zoom at the maximum level the tile should not load and be all gray. When zooming out it should still be gray until some level (~12 I think).

This bug should appear in most configuration. However, I was not able to reproduce it on a windows desktop computer with chrome.

**Comment by barbeau** [comment]
@jailby if you're having issues reproducing, why don't you move on to some of the other more critical issues, like https://github.com/CUTR-at-USF/usf-mobullity/issues/70.  We can always come back to this one.

**Comment by barbeau** [comment]
Just checked the changelog for Leaflet - looks like this may be a bug fixed in Leaflet 0.7.4:
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#074-september-1-2015

> Fixed a bug where tile layers were not respecting their minZoom or maxZoom options (by @ivansanchez) #3778

We're currently using Leaflet 0.7.3:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/lib/leaflet/leaflet-src.js#L10

Most recent stable release is 0.7.5:
http://leafletjs.com/download.html

So, I'm betting if we update to Leaflet 0.7.5 it will fix this problem.

**Comment by jailby** [comment]
According to what @jmfield2 saw on the leaflet repository it is an upstream fixed issue. Thus updating leaflet should fix this problem.

**Comment by jailby** [comment]
If we change the [maxim zoom](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L74) to 18 or 19 this bug should not be present anymore.

I tested it and it work. We just need to make sure this maxim zoom is not too zoomed out.

**Comment by jailby** [comment]
Closed because fixed:
https://github.com/CUTR-at-USF/usf-mobullity/commit/52e97f0448319951ade0b258f9fa158200cedc86
