### ISSUE TITLE
My location button is needed

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#70]
A button "My location" that would cause the user to share his location then the map to center on this location is needed. 

Similar to the button on the one bus away application.

An issue has been created to have the possibility to select the current location of the user but this button would enable more functionality for the user.
https://github.com/CUTR-at-USF/usf-mobullity/issues/40

**Comment by barbeau** [comment]
+1 for this - it's very important, especially on mobile.  Let's prioritize this.

One question is how the real-time location button actually looks - here's how it looks on Google Maps on desktop:

![image](https://cloud.githubusercontent.com/assets/928045/9609478/d3cbea7e-50a1-11e5-8992-f70e2822d216.png)

I think something similar with the cross-hairs should work.  We should probably stick to something close to what appears in the browser address bar to indicate real-time location, since MoBullity users will also see this.

@jailby For icons for this, I'd suggest checking:
- Android Icon Generator (click on Clip Art, and scroll down a bit) - https://romannurik.github.io/AndroidAssetStudio/icons-generic.html#source.space.trim=1&source.space.pad=0&size=24&padding=8&color=33b5e5%2C100&name=ic_example
- The Noun Project - https://thenounproject.com/search/?q=location

For the Noun Project, we'd just need to confirm that the individual icon license is ok for us to use (people who upload these define their license).

**Comment by jailby** [comment]
Which one do you prefer:
1) https://thenounproject.com/search/?q=location&i=141972
2) https://thenounproject.com/search/?q=location&i=156845
3) https://thenounproject.com/search/?q=location&i=182952
4) https://thenounproject.com/search/?q=location&i=19027
5) https://thenounproject.com/search/?q=location&i=91560
They are all under creative common.

I selected a few that look good and are under CC. We can always change it in the future.

**Comment by jmfield2** [comment]
Looks like a leaflet plugin might help implement this:
https://github.com/domoritz/leaflet-locatecontrol

_edit_ Yeah I agree it's related to #40 at least insofar as if the locate start/end can or should reference any previously loaded locations or if it should always try to get fresh coordinates... or if the control will actively track gps

**Comment by barbeau** [comment]
Plugin looks nice, but doesn't seem to work on Chome?  Try the [demo link](http://domoritz.github.io/leaflet-locatecontrol/demo/) in the README and see if you get the same result.

If we add the "My Location" button, I don't think the map should always re-position itself to the real-time user location.  We've tried this in other apps and it ends up being awkward.  So my vote is for only repositioning the map to the user's real-time location when:
1. They click/tap to share their location
2. They click/tap the My Location button

Other than that, the only time we move the map is when the user plans a trip, to show the entire trip on the map, and on initial load.

For icons, https://thenounproject.com/search/?q=location&i=19027 seems to be the closest to the Chrome address bar location icon.  I'd prefer something like this, whether its via the plugin or in our own button.

**Comment by jailby** [comment]
@jmfield2 I have been trying to find the code for the widget that allow the user to zoom in and out. I have been unsuccessful yet. Do you know where it is or have a idea of where it could be?

**Comment by jmfield2** [comment]
This should be part of leaflet I think and configured by map.js with the
zoomControl config option

To add the my location you'll need to make a new control and add it to the
map like the other project (whose demo was broke) that I linked above
probably

**Comment by jailby** [comment]
I did find the configuration in Map.js at the [line 167](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/Map.js#L167).
This seem to just position the widget. I was atually looking for the code that do the zoom in/out.

Like when it does "L.control.zoom" where does the "zoom" come from. I'm reading more about leaflet so I might found out at some point.

**Comment by jmfield2** [comment]
Ya - that should be somewhere in leaflet .. There is a github that might be
easier

Good luck lol

**Comment by jailby** [comment]
Yeah I'm reading stuff from the github and the leaflet documentation.

**Comment by cagryInside** [comment]
Look at this post:

http://stackoverflow.com/questions/23016863/adding-an-external-find-my-location-button-outside-of-the-map

**Comment by jailby** [comment]
https://github.com/domoritz/leaflet-locatecontrol#methods

**Comment by cagryInside** [comment]
Look at this post:

http://stackoverflow.com/questions/23016863/adding-an-external-find-my-location-button-outside-of-the-map

Edit:
http://codepen.io/leemark/pen/vcbuf

**Comment by jailby** [comment]
@barbeau I tried the [leaflet plugin demo](http://domoritz.de/leaflet-locatecontrol/demo/) with chrome on both my Linux Mint laptop and the desktop windows 7 computer and it was working.
Can you check again if it is not working for you and let me know what's wrong with it.

If it is actually working it is probably or best solution. Otherwise, we would have to create the widget and position it correctly according to the other buttons.

**Comment by barbeau** [comment]
@jailby Seems to be working for me now on Chrome.  Maybe it was a temporary issue.

**Comment by jmfield2** [comment]
I think https://github.com/CUTR-at-USF/usf-mobullity/pull/95 should fix the remaining issues with the locate btn
