### ISSUE TITLE
Zoom on trip to close on low resolutions

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#74]
We decided to center the view on the trip planned by the user and it has been fixed in #45 which works.

However, on low resolution screen the view is sometimes too zoomed in and to have a useful view of the map the user need to zoom out.

If we just change the attribute to be zoom out a bit more this might generate problem for higher resolution screens. Higher resolution screen would have a view too zoomed out.

The solution would be to adapt the view depending on the screen resolution of the user. 

This happened after PR #72

**Comment by jmfield2** [comment]
Cleaning up the src/client/js/otp/config.js zoom levels seems to have fixed this issue in my testing. 

@jailby can you test and confirm that the PR fixes this?
