### ISSUE TITLE
Internet Explorer not working

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#75]
On the windows computer provided by CUTR, mobulity is not working using **IE**.

The computer is **desktop** computer running **Microsoft Windows 7 Enterprise**:
Version 6.1.7601 Service Pack 1 Build 7601
Processor   Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz, 2933 Mhz, 2 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM) 2.00 GB

**Internet Explorer** version: 8.0

The following screenshot is what I see:
![image](https://cloud.githubusercontent.com/assets/1370401/9909295/967b18dc-5c65-11e5-8a35-8de22959a5ee.png)

The problem seem to be located at: js/lib/respond.min.js line 6 character 2632.
I need more time to investigate on this issue and I will updated this issue with my findings.

This version is used a lot (10% of total traffic):
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

**Comment by barbeau** [comment]
It seems to work fine on IE 11 on my work machine.  Would be good to get
others to try different versions too.

**Comment by jailby** [comment]
IE8 is not working because the following line of code is commented:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/index.html#L36



Updating leaflet should fix this problem since they don't use a separate file for IE8 and therefore this three lines should be deleted.

**Comment by jmfield2** [comment]
IE11 on Win7 is working, and IE8 on WinXP works on opentripplanner.usf.edu, and other leaflet demos, but not mobullity, or even upstream otp-0.18.0.

The main difference seems to be jQuery, and that IE8 is failing to load the client-side templates via JS and also failing to initialize the OTP webapp.

The only other option I can think of besides trying to track this down is to look into the conveyal otp.js app, but it's probably too major for now.

**Comment by jailby** [comment]
I also asked the IT desk and the following is their answer:

> Hello,
> 
> In general, Internet Explorer 9 is likely to be the lowest version found on most USF machines, however some individuals may still be using Internet Explorer 8 if they require it for a specific reason associated with their job duties. USF IT doesn't have a specific record of which machines are running IE version 8. Is there a specific area on campus you are concerned about? If so, provide us with the building code and any associated room numbers, and the technicians that support that area can provide you with more information.

**Comment by barbeau** [comment]
@jailby Do you know if Mobullity works with IE9?

**Comment by jailby** [comment]
Not sure but when I looked into this problem it seem that other related problems were having this problem specifically for IE 8.

I am assuming that it should work for IE 9 but I don't have it. I can stop by the library/MSC one day to make sure. Let me know if you want me to.

**Comment by barbeau** [comment]
Yes, let's confirm whether or not it works for IE9.

**Comment by jmfield2** [comment]
Confirm that IE9 works on Windows 7 (via modern.ie VM)

**Comment by jailby** [comment]
Thank you. I forgot to do it.
