### ISSUE TITLE
Opera not properly working

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#76]
On the windows computer provided by CUTR, mobulity is not working using **Opera**.

The computer is **desktop** computer running **Microsoft Windows 7 Enterprise**:
Version 6.1.7601 Service Pack 1 Build 7601
Processor   Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz, 2933 Mhz, 2 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM) 2.00 GB

**Opera** version: 32.0

The following screenshot is what I see when it is working:
![image](https://cloud.githubusercontent.com/assets/1370401/9910312/84285ec4-5c6a-11e5-9ad0-08f8484bb19e.png)

This screenshot is what happen when I try to have a more zoomed in view and try to do things:
![image](https://cloud.githubusercontent.com/assets/1370401/9910236/0c9dda3c-5c6a-11e5-9dab-45240709bca6.png)

Opera windows version seems up to date. Any of you @barbeau @jmfield2 have opera installed on a windows computer and can post what you see?

I don't have this kind of problem using Opera under Linux Mint 17.1 on my laptop.

**Comment by barbeau** [comment]
I don't have Opera installed - I'll see if I can install it.

**Comment by jailby** [comment]
Opera did not work then but work for me again right now.

Since, this issue seem to not be able to be reproduce and the potential number of user affect by such bug is really low, I'm closing the issue.

**Comment by jailby** [comment]
Opera did not work then but work for me again right now and Friday.

Since, this issue seem to not be able to be reproduce and the potential number of user affect by such bug is really low, I'm closing the issue.
