### ISSUE TITLE
SocialBicycles Updater

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#79]
- Merge and update the bike_rental code
- Final stability testing

Currently there are only a handful of hubs listed from the API and they include data from several available racks (via geographic clustering - e.g: one hub @ MSC lists available bikes for the north, east, and south racks nearby)

With that said, it may be better to route users to individual bikes instead at least to pickup, and they can drop the bike anywhere... 

Perhaps it is OK to drop at another 'bike' since it is probably at a rack anyway (like it does now).

**Comment by barbeau** [comment]
I got this info this week from Francis Morgan at Campus Rec:

> Over the weekend I learned that GPS coverage of campus is weak. We eliminated all but a few hubs and eliminated the out of hub fee (=$0). The hubs we will maintain are related to the perimeter parking lots and parking garages for rebalancing. There is a $1 incentive to lock a bike in the remaining hubs. Green dollar amounts on a person’s account are credits toward future use. Red dollar amounts are charges. We are currently contacting those who incur a fee and let them know what wasn’t correct and reversing the charge.

Upon further discussion it sounds like when bikes are docked near buildings, they are calculating a GPS position once per hour, and simply grabbing and using the first GPS fix.  The problem with this approach is that the initial fix can be very inaccurate - apparently the company is working on changing this to do some averaging over a few fixes, or another solution to help fix this issue.

In the mean time, though, apparently USF is going to function as one big zone - so, there is no penalty for dropping the bike anywhere on campus.

**Comment by jmfield2** [comment]
NOTE: SocialBicycles announced support for new "GBFS" opendata JSON endpoints on Friday November 6, 2015 @ 
http://usf.socialbicycles.com/opendata
Tampa's Coast is also available @ http://coast.socialbicycles.com/opendata

A simple JSON updater will be pushed this week to implement support for this as well as the original OAuth structure.
