### ISSUE TITLE
USF PATS request - Add Parking and Transportation Services as POI

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#97]
A high priority POI - we definitely need to add Parking and Transportation Services (PTA and PTB) - see this map:
http://www.usf.edu/administrative-services/parking/documents/campus-map-directory.pdf

@jailby Could you please do this for both the POI directory in MoBullity and also label the buildings in OpenStreetMap, if they aren't already?

**Comment by jailby** [comment]
Ok, I will take care of this.

**Comment by jailby** [comment]
PTA is present in OSM but does not show up:
https://www.openstreetmap.org/node/367824927

**Comment by barbeau** [comment]
Fixed via https://github.com/CUTR-at-USF/usf-mobullity/pull/102.
