### ISSUE TITLE
USF PATS request - Change default max walk in trip planner GUI

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#98]
After talking with USF Parking and Transportation Services (PATS) today, we should change the default "Maximum walk" parameter in the trip planning screen from `1.00` to `0.3`.  At values from `1.0` to `0.4`, OTP only returns a single trip itinerary (walk).  When you change to `0.3`, it provides at least 2 trip itineraries, where the first is walk and the 2nd is Bull Runner.  USF PATS walks to always display the bus option along with walk if possible.

@jailby Could you please tackle this?

**Comment by barbeau** [comment]
Also, this is a high priority issue.

**Comment by jailby** [comment]
OK so I think I found where is the attribute in the project:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/modules/planner/PlannerModule.js#L24

I believe that I need to modify all three of these attributes:

```
    maxWalkDistance                 : 1609.34, // 1 mile
    metricDefaultMaxWalkDistance    : 750, // meters
    imperialDefaultMaxWalkDistance  : 1609.34, // 1 mile
```

@barbeau The `1.00` in your comment refer to `1.00` **mile** right? Therefore, it need to be changed to `0.3` **miles**.

@jmfield2 I'm a little bit confuse by the values, and their units, of these attributes.
`1.00` **mile** = `1609.34` **meters**
I assume that `maxWalkDistance` unit is in meter because it is set to `1609.34`.
`metricDefaultMaxWalkDistance` is set to `750`, but if the unit is in meter it should be set to `1609.34` to correspond to `1.00` mile.
`imperialDefaultMaxWalkDistance` is set to `1609.34` but this is probably wrong and I have no idea what is the unit of this attribute. What is the unit of reference in the imperial system? `1.00` mile in yards is `1760` fyi.

**Comment by barbeau** [comment]
@jailby Yes, my request was to change `1.00` miles to `0.3` miles.

Yes, that doesn't seem to make sense.  With the current settings, it seems `imperialDefaultMaxWalkDistance` should be set to `1`.

I'm guessing `maxWalkDistance` is the metric shown in the Trip Planner Leaflet UI (but converted to mlies)?

When using `0.3` in the UI for max walk distance, here's the URL that's generated:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=(CUT)%20Center%20for%20Urban%20Transportation%20Research%3A%3A28.0586%2C-82.4161&toPlace=(MSC)%20Marshall%20Student%20Center%3A%3A28.0638%2C-82.4135&time=11%3A25am&date=10-21-2015&mode=TRANSIT%2CWALK&maxWalkDistance=482.80199999999996&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0

So looks like this is converted to meters for submitting to the REST API (`482` is ~1/3 of `1609.34`).

**Comment by jailby** [comment]
`metricDefaultMaxWalkDistance` and `imperialDefaultMaxWalkDistance` are only used in [this condition](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/modules/planner/PlannerModule.js#L110).

Solely changing `maxWalkDistance` to `482.8032` which is ~`0.3` miles does not fix the problem.

It doesn't change anything because in any cases `maxWalkDistance` will be update to either `metricDefaultMaxWalkDistance` or `imperialDefaultMaxWalkDistance` because of the condition stated previously.

**Comment by barbeau** [comment]
Here's the code block that @jailby is referencing:

```
 if (otp.config.metric) {
            this.defaultQueryParams.maxWalkDistance = this.defaultQueryParams.metricDefaultMaxWalkDistance;
        } else {
            this.defaultQueryParams.maxWalkDistance = this.defaultQueryParams.imperialDefaultMaxWalkDistance;
        }
```

Looks like this is what switches between metric and imperial based on the OTP config for the server.

Here's the URL that's created when using the default settings:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=(CUT)%20Center%20for%20Urban%20Transportation%20Research%3A%3A28.0586%2C-82.4161&toPlace=(MSC)%20Marshall%20Student%20Center%3A%3A28.0638%2C-82.4135&time=11%3A56am&date=10-21-2015&mode=TRANSIT%2CWALK&maxWalkDistance=1609.34&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0

Based on both of the above, it looks like `imperialDefaultMaxWalkDistance` is what is setting the `1.00` mile value?

**Comment by jailby** [comment]
@barbeau Yes I assume that's right.

**Comment by barbeau** [comment]
@jailby Can you try changing `imperialDefaultMaxWalkDistance` to `482.8032` and see if that works?

**Comment by jmfield2** [comment]
It looks like the 1.0 is coming from modules planner PlannerModule default
query params maxwalkdistance

And is converted into the 1.0 at runtime by geo.distance string (i think)

It is either that variable or the imperial/metric default maxwalkdistance
that Sean said also inside of PlannerModule

**Comment by jailby** [comment]
Yes, changing `imperialDefaultMaxWalkDistance` to `482.8032` works.

Should I do just that or cleanup the code a bit.

I would prefer to change `maxWalkDistance` to `482.8032` and delete the two other attributes and the condition.

**Comment by barbeau** [comment]
@jailby My feeling is they probably need to stay if we allow units to change.  And, if we want to stay close to upstream OTP, we should keep those.  So I'd stick with just chaging `imperialDefaultMaxWalkDistance` if that works.  Unless @jmfield2 thinks differently.

**Comment by jailby** [comment]
@barbeau These two attributes don't seem to be present anymore in upstream OTP:
https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/client/otpa/js/Widgets.js#L43

It bother me a bit that the `imperialDefaultMaxWalkDistance` unit is in meter.

**Comment by barbeau** [comment]
OK, if it's a cleanup to match upstream that makes sense to me.  And
changing units to correct value also makes sense.

**Comment by jmfield2** [comment]
Sounds fine to me too. I was about to say the same re upstream and allowing
units to change but..yeah lol

**Comment by barbeau** [comment]
@jailby I think you were looking at the wrong module - here in upstream they still have the other two fields:

https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/client/js/otp/modules/planner/PlannerModule.js

**Comment by jailby** [comment]
True. 

You want me to change both `maxWalkDistance` and `imperialDefaultMaxWalkDistance` to `482.8032`?
To be consistent with upstream. 

Can I ask them why they have `imperialDefaultMaxWalkDistance` in **meters**?

**Comment by barbeau** [comment]
> You want me to change both maxWalkDistance and imperialDefaultMaxWalkDistance to 482.8032?

Yes.  You should probably change `metricDefaultMaxWalkDistance` to this value as well to be consistent.  See below.

@jmfield2 Do you know if otp.config pulls any browser locale settings to default to metric vs. imperial?  My impression was that this was hard-coded into the server config, but it would make more sense for it to be dynamic based on browser locale.  So, if an international student has their browser default set to a locale for metric, they would see metric?  We don't need to change the current behavior, but it would be good to know if `metricDefaultMaxWalkDistance` would ever be used in our current deployment.

> Can I ask them why they have imperialDefaultMaxWalkDistance in meters?

So I think all internal variables need to be in meters so they can be passed to OTP, which uses metric internally.  `imperialDefaultMaxWalkDistance` is just a secondary default variable, driven by the choice of unit system.  So, it allows them to have different default values for metric and imperial - I'm not sure why that exists, so I think that's the question I would ask ("Why are there different default values for maxWalk parameter for imperial vs. metric configuration?".  But, the imperial variable itself still needs to be in meters, so it can be input into OTP.

**Comment by jailby** [comment]
> So I think all internal variables need to be in meters

If this is the case I don't understand why there should be these two attributes. If both need to be in meter and both represent the `maxWalkDistance` they should be the same value and therefore will be useless.
These attributes are use to update `maxWalkDistance` and if in any case they update it to the same value there is no need of such attributes.

@barbeau I'm going to write the question and send it to you like that you can review it and if there is any edit to do you can let me know.
